#!/usr/bin/env python3
"""Remaining UI string translations for Localizable.xcstrings generation."""

from __future__ import annotations


def apply_rest(T: dict[str, dict[str, str]]) -> None:
    T.update(
        {
            "severity.low": {
                "en": "LOW",
                "tr": "DÜŞÜK",
                "es": "BAJA",
                "es-419": "BAJA",
                "pt-BR": "BAIXA",
                "pt-PT": "BAIXA",
                "hi": "कम",
                "id": "RENDAH",
                "ar": "منخفض",
                "ru": "НИЗКАЯ",
                "de": "NIEDRIG",
                "fr": "FAIBLE",
                "ja": "低",
                "ko": "낮음",
                "zh-Hans": "低",
                "zh-Hant": "低",
                "vi": "THẤP",
                "th": "ต่ำ",
                "it": "BASSA",
                "pl": "NISKI",
                "nl": "LAAG",
                "ms": "RENDAH",
                "fil": "MABABA",
                "ur": "کم",
                "bn": "কম",
                "fa": "کم",
                "uk": "НИЗЬКА",
                "ro": "SCĂZUTĂ",
                "cs": "NÍZKÁ",
                "sv": "LÅG",
                "el": "ΧΑΜΗΛΗ",
                "he": "נמוך",
                "hu": "ALACSONY",
                "da": "LAV",
                "fi": "MATALA",
                "nb": "LAV",
                "sk": "NÍZKA",
                "hr": "NISKA",
                "bg": "НИСКА",
                "sw": "CHINI",
                "ca": "BAIXA",
            },
            "severity.medium": {
                "en": "MEDIUM",
                "tr": "ORTA",
                "es": "MEDIA",
                "es-419": "MEDIA",
                "pt-BR": "MÉDIA",
                "pt-PT": "MÉDIA",
                "hi": "मध्यम",
                "id": "SEDANG",
                "ar": "متوسط",
                "ru": "СРЕДНЯЯ",
                "de": "MITTEL",
                "fr": "MOYENNE",
                "ja": "中",
                "ko": "보통",
                "zh-Hans": "中",
                "zh-Hant": "中",
                "vi": "TRUNG BÌNH",
                "th": "ปานกลาง",
                "it": "MEDIA",
                "pl": "ŚREDNI",
                "nl": "GEMIDDELD",
                "ms": "SEDERHANA",
                "fil": "KATAMTAMAN",
                "ur": "درمیانہ",
                "bn": "মাঝারি",
                "fa": "متوسط",
                "uk": "СЕРЕДНЯ",
                "ro": "MEDIE",
                "cs": "STŘEDNÍ",
                "sv": "MEDEL",
                "el": "ΜΕΤΡΙΑ",
                "he": "בינוני",
                "hu": "KÖZEPES",
                "da": "MIDDEL",
                "fi": "KESKITASO",
                "nb": "MIDDELS",
                "sk": "STREDNÁ",
                "hr": "SREDNJA",
                "bg": "СРЕДНА",
                "sw": "WASTANI",
                "ca": "MITJANA",
            },
            "severity.high": {
                "en": "HIGH",
                "tr": "YÜKSEK",
                "es": "ALTA",
                "es-419": "ALTA",
                "pt-BR": "ALTA",
                "pt-PT": "ALTA",
                "hi": "उच्च",
                "id": "TINGGI",
                "ar": "مرتفع",
                "ru": "ВЫСОКАЯ",
                "de": "HOCH",
                "fr": "ÉLEVÉE",
                "ja": "高",
                "ko": "높음",
                "zh-Hans": "高",
                "zh-Hant": "高",
                "vi": "CAO",
                "th": "สูง",
                "it": "ALTA",
                "pl": "WYSOKI",
                "nl": "HOOG",
                "ms": "TINGGI",
                "fil": "MATAAS",
                "ur": "زیادہ",
                "bn": "উচ্চ",
                "fa": "بالا",
                "uk": "ВИСОКА",
                "ro": "RIDICATĂ",
                "cs": "VYSOKÁ",
                "sv": "HÖG",
                "el": "ΥΨΗΛΗ",
                "he": "גבוה",
                "hu": "MAGAS",
                "da": "HØJ",
                "fi": "KORKEA",
                "nb": "HØY",
                "sk": "VYSOKÁ",
                "hr": "VISOKA",
                "bg": "ВИСОКА",
                "sw": "JUU",
                "ca": "ALTA",
            },
            "severity.critical": {
                "en": "CRITICAL",
                "tr": "KRİTİK",
                "es": "CRÍTICA",
                "es-419": "CRÍTICA",
                "pt-BR": "CRÍTICA",
                "pt-PT": "CRÍTICA",
                "hi": "गंभीर",
                "id": "KRITIS",
                "ar": "حرج",
                "ru": "КРИТИЧЕСКАЯ",
                "de": "KRITISCH",
                "fr": "CRITIQUE",
                "ja": "重大",
                "ko": "심각",
                "zh-Hans": "严重",
                "zh-Hant": "嚴重",
                "vi": "NGHIÊM TRỌNG",
                "th": "วิกฤต",
                "it": "CRITICA",
                "pl": "KRYTYCZNY",
                "nl": "KRITIEK",
                "ms": "KRITIKAL",
                "fil": "KRITIKAL",
                "ur": "تشویشناک",
                "bn": "সংকটজনক",
                "fa": "بحرانی",
                "uk": "КРИТИЧНА",
                "ro": "CRITICĂ",
                "cs": "KRITICKÁ",
                "sv": "KRITISK",
                "el": "ΚΡΙΣΙΜΗ",
                "he": "קריטי",
                "hu": "KRITIKUS",
                "da": "KRITISK",
                "fi": "KRIITTINEN",
                "nb": "KRITISK",
                "sk": "KRITICKÁ",
                "hr": "KRITIČNA",
                "bg": "КРИТИЧНА",
                "sw": "MUHIMU",
                "ca": "CRÍTICA",
            },
            "result.steps": {
                "en": "Repair steps",
                "tr": "Tamir adımları",
                "es": "Pasos de reparación",
                "es-419": "Pasos de reparación",
                "pt-BR": "Passos de reparo",
                "pt-PT": "Passos de reparação",
                "hi": "मरम्मत के चरण",
                "id": "Langkah perbaikan",
                "ar": "خطوات الإصلاح",
                "ru": "Шаги ремонта",
                "de": "Reparaturschritte",
                "fr": "Étapes de réparation",
                "ja": "修理手順",
                "ko": "수리 단계",
                "zh-Hans": "维修步骤",
                "zh-Hant": "維修步驟",
                "vi": "Các bước sửa chữa",
                "th": "ขั้นตอนการซ่อม",
                "it": "Passaggi di riparazione",
                "pl": "Kroki naprawy",
                "nl": "Reparatiestappen",
                "ms": "Langkah pembaikan",
                "fil": "Mga hakbang sa pagkumpuni",
                "ur": "مرمت کے مراحل",
                "bn": "মেরামতের ধাপ",
                "fa": "مراحل تعمیر",
                "uk": "Кроки ремонту",
                "ro": "Pași de reparație",
                "cs": "Kroky opravy",
                "sv": "Reparationssteg",
                "el": "Βήματα επισκευής",
                "he": "שלבי תיקון",
                "hu": "Javítási lépések",
                "da": "Reparationstrin",
                "fi": "Korjausvaiheet",
                "nb": "Reparasjonstrinn",
                "sk": "Kroky opravy",
                "hr": "Koraci popravka",
                "bg": "Стъпки за ремонт",
                "sw": "Hatua za ukarabati",
                "ca": "Passos de reparació",
            },
            "result.videos": {
                "en": "Community videos",
                "tr": "Topluluk videoları",
                "es": "Vídeos de la comunidad",
                "es-419": "Videos de la comunidad",
                "pt-BR": "Vídeos da comunidade",
                "pt-PT": "Vídeos da comunidade",
                "hi": "समुदाय वीडियो",
                "id": "Video komunitas",
                "ar": "فيديوهات المجتمع",
                "ru": "Видео сообщества",
                "de": "Community-Videos",
                "fr": "Vidéos de la communauté",
                "ja": "コミュニティ動画",
                "ko": "커뮤니티 영상",
                "zh-Hans": "社区视频",
                "zh-Hant": "社群影片",
                "vi": "Video cộng đồng",
                "th": "วิดีโอจากชุมชน",
                "it": "Video della community",
                "pl": "Filmy społeczności",
                "nl": "Communityvideo’s",
                "ms": "Video komuniti",
                "fil": "Mga video ng komunidad",
                "ur": "کمیونٹی ویڈیوز",
                "bn": "কমিউনিটি ভিডিও",
                "fa": "ویدیوهای انجمن",
                "uk": "Відео спільноти",
                "ro": "Videoclipuri din comunitate",
                "cs": "Videa komunity",
                "sv": "Communityvideor",
                "el": "Βίντεο κοινότητας",
                "he": "סרטוני קהילה",
                "hu": "Közösségi videók",
                "da": "Fællesskabsvideoer",
                "fi": "Yhteisön videot",
                "nb": "Fellesskapsvideoer",
                "sk": "Videá komunity",
                "hr": "Videozapisi zajednice",
                "bg": "Видеа от общността",
                "sw": "Video za jumuiya",
                "ca": "Vídeos de la comunitat",
            },
            "result.videos.empty": {
                "en": "No videos yet — be the first to upload.",
                "tr": "Henüz video yok — ilk yükleyen sen ol.",
                "es": "Aún no hay vídeos — sé el primero en subir uno.",
                "es-419": "Aún no hay videos — sé el primero en subir uno.",
                "pt-BR": "Ainda não há vídeos — seja o primeiro a enviar.",
                "pt-PT": "Ainda não há vídeos — seja o primeiro a carregar.",
                "hi": "अभी कोई वीडियो नहीं — पहले अपलोड करने वाले बनें।",
                "id": "Belum ada video — jadilah yang pertama mengunggah.",
                "ar": "لا توجد فيديوهات بعد — كن أول من يرفع.",
                "ru": "Пока нет видео — загрузите первым.",
                "de": "Noch keine Videos — laden Sie als Erste:r hoch.",
                "fr": "Pas encore de vidéos — soyez le premier à en importer.",
                "ja": "まだ動画がありません — 最初にアップロードしましょう。",
                "ko": "아직 영상이 없습니다 — 첫 업로드를 해보세요.",
                "zh-Hans": "暂无视频 — 成为第一个上传的人。",
                "zh-Hant": "尚無影片 — 成為第一個上傳的人。",
                "vi": "Chưa có video — hãy là người đầu tiên tải lên.",
                "th": "ยังไม่มีวิดีโอ — เป็นคนแรกที่อัปโหลด",
                "it": "Nessun video ancora — sii il primo a caricarne uno.",
                "pl": "Brak filmów — bądź pierwszą osobą, która prześle.",
                "nl": "Nog geen video’s — wees de eerste die uploadt.",
                "ms": "Belum ada video — jadilah yang pertama memuat naik.",
                "fil": "Wala pang video — maging una sa pag-upload.",
                "ur": "ابھی کوئی ویڈیو نہیں — سب سے پہلے اپ لوڈ کریں۔",
                "bn": "এখনও কোনো ভিডিও নেই — প্রথম আপলোডকারী হোন।",
                "fa": "هنوز ویدیویی نیست — اولین نفر باشید که آپلود می‌کند.",
                "uk": "Поки немає відео — завантажте першим.",
                "ro": "Încă nu există videoclipuri — fii primul care încarcă.",
                "cs": "Zatím žádná videa — buďte první, kdo nahraje.",
                "sv": "Inga videor ännu — bli först att ladda upp.",
                "el": "Δεν υπάρχουν ακόμη βίντεο — ανεβάστε πρώτοι.",
                "he": "עדיין אין סרטונים — היו הראשונים להעלות.",
                "hu": "Még nincsenek videók — legyen Ön az első feltöltő.",
                "da": "Ingen videoer endnu — vær den første til at uploade.",
                "fi": "Ei vielä videoita — ole ensimmäinen lataaja.",
                "nb": "Ingen videoer ennå — vær først til å laste opp.",
                "sk": "Zatiaľ žiadne videá — buďte prvý, kto nahrá.",
                "hr": "Još nema videozapisa — budi prvi koji učita.",
                "bg": "Все още няма видеа — бъдете първият, който качи.",
                "sw": "Bado hakuna video — kuwa wa kwanza kupakia.",
                "ca": "Encara no hi ha vídeos — sigues el primer a pujar-ne un.",
            },
            "result.view3d": {
                "en": "View faulty part in 3D",
                "tr": "Arızalı parçayı 3D’de gör",
                "es": "Ver la pieza defectuosa en 3D",
                "es-419": "Ver la pieza defectuosa en 3D",
                "pt-BR": "Ver a peça com falha em 3D",
                "pt-PT": "Ver a peça com avaria em 3D",
                "hi": "दोषपूर्ण पार्ट को 3D में देखें",
                "id": "Lihat suku cadang bermasalah dalam 3D",
                "ar": "عرض القطعة المعطلة بتقنية ثلاثية الأبعاد",
                "ru": "Посмотреть неисправную деталь в 3D",
                "de": "Defektes Teil in 3D anzeigen",
                "fr": "Voir la pièce défectueuse en 3D",
                "ja": "故障部品を3Dで表示",
                "ko": "고장 부품을 3D로 보기",
                "zh-Hans": "以 3D 查看故障零件",
                "zh-Hant": "以 3D 查看故障零件",
                "vi": "Xem phụ tùng lỗi ở dạng 3D",
                "th": "ดูอะไหล่ที่ชำรุดแบบ 3D",
                "it": "Visualizza il pezzo difettoso in 3D",
                "pl": "Zobacz uszkodzoną część w 3D",
                "nl": "Bekijk het defecte onderdeel in 3D",
                "ms": "Lihat bahagian rosak dalam 3D",
                "fil": "Tingnan ang sira na parte sa 3D",
                "ur": "خراب پرزہ 3D میں دیکھیں",
                "bn": "ত্রুটিপূর্ণ যন্ত্রাংশ 3D-তে দেখুন",
                "fa": "قطعه معیوب را سه‌بعدی ببینید",
                "uk": "Переглянути несправну деталь у 3D",
                "ro": "Vezi piesa defectă în 3D",
                "cs": "Zobrazit vadný díl ve 3D",
                "sv": "Visa felaktig del i 3D",
                "el": "Προβολή ελαττωματικού εξαρτήματος σε 3D",
                "he": "הצג חלק פגום בתלת־ממד",
                "hu": "Hibás alkatrész megtekintése 3D-ben",
                "da": "Se den defekte del i 3D",
                "fi": "Näytä viallinen osa 3D:nä",
                "nb": "Vis defekt del i 3D",
                "sk": "Zobraziť chybný diel v 3D",
                "hr": "Pogledaj neispravan dio u 3D",
                "bg": "Вижте повредената част в 3D",
                "sw": "Angalia sehemu yenye hitilafu kwa 3D",
                "ca": "Mostra la peça defectuosa en 3D",
            },
            "scene3d.title": {
                "en": "Highlighted part",
                "tr": "Vurgulanan parça",
                "es": "Pieza resaltada",
                "es-419": "Pieza resaltada",
                "pt-BR": "Peça destacada",
                "pt-PT": "Peça destacada",
                "hi": "हाइलाइट किया गया पार्ट",
                "id": "Suku cadang yang disorot",
                "ar": "القطعة المميزة",
                "ru": "Выделенная деталь",
                "de": "Hervorgehobenes Teil",
                "fr": "Pièce mise en évidence",
                "ja": "強調表示された部品",
                "ko": "강조된 부품",
                "zh-Hans": "高亮零件",
                "zh-Hant": "醒目零件",
                "vi": "Phụ tùng được tô sáng",
                "th": "อะไหล่ที่ไฮไลต์",
                "it": "Pezzo evidenziato",
                "pl": "Podświetlona część",
                "nl": "Gemarkeerd onderdeel",
                "ms": "Bahagian diserlahkan",
                "fil": "Naka-highlight na parte",
                "ur": "نمایاں پرزہ",
                "bn": "হাইলাইট করা যন্ত্রাংশ",
                "fa": "قطعه برجسته‌شده",
                "uk": "Виділена деталь",
                "ro": "Piesă evidențiată",
                "cs": "Zvýrazněný díl",
                "sv": "Markerad del",
                "el": "Επισημασμένο εξάρτημα",
                "he": "חלק מודגש",
                "hu": "Kiemelt alkatrész",
                "da": "Fremhævet del",
                "fi": "Korostettu osa",
                "nb": "Uthevet del",
                "sk": "Zvýraznený diel",
                "hr": "Istaknuti dio",
                "bg": "Маркирана част",
                "sw": "Sehemu iliyoangaziwa",
                "ca": "Peça destacada",
            },
            "scene3d.hint": {
                "en": "Drag to rotate. Orange mark shows the likely faulty component.",
                "tr": "Döndürmek için sürükle. Turuncu işaret olası arızalı parçayı gösterir.",
                "es": "Arrastra para rotar. La marca naranja indica el componente probablemente defectuoso.",
                "es-419": "Arrastra para rotar. La marca naranja indica el componente probablemente defectuoso.",
                "pt-BR": "Arraste para girar. A marca laranja mostra o componente provavelmente com falha.",
                "pt-PT": "Arraste para rodar. A marca laranja mostra o componente provavelmente com avaria.",
                "hi": "घुमाने के लिए खींचें। नारंगी चिह्न संभावित दोषपूर्ण घटक दिखाता है।",
                "id": "Seret untuk memutar. Tanda oranye menunjukkan komponen yang kemungkinan bermasalah.",
                "ar": "اسحب للتدوير. العلامة البرتقالية تُظهر المكوّن المحتمل تعطله.",
                "ru": "Перетащите для вращения. Оранжевая метка показывает вероятную неисправную деталь.",
                "de": "Zum Drehen ziehen. Orange Markierung zeigt das vermutlich defekte Bauteil.",
                "fr": "Faites glisser pour faire pivoter. Le repère orange indique le composant probablement défectueux.",
                "ja": "ドラッグで回転。オレンジの印が故障の可能性がある部品を示します。",
                "ko": "드래그하여 회전하세요. 주황 표시가 고장 가능성이 있는 부품을 나타냅니다.",
                "zh-Hans": "拖动以旋转。橙色标记显示可能的故障部件。",
                "zh-Hant": "拖曳以旋轉。橘色標記顯示可能故障的零件。",
                "vi": "Kéo để xoay. Dấu cam cho thấy linh kiện có thể bị lỗi.",
                "th": "ลากเพื่อหมุน เครื่องหมายสีส้มแสดงชิ้นส่วนที่น่าจะชำรุด",
                "it": "Trascina per ruotare. Il segno arancione indica il componente probabilmente difettoso.",
                "pl": "Przeciągnij, aby obrócić. Pomarańczowe oznaczenie wskazuje prawdopodobnie uszkodzony element.",
                "nl": "Sleep om te draaien. Oranje markering toont het waarschijnlijk defecte onderdeel.",
                "ms": "Seret untuk putar. Tanda jingga menunjukkan komponen yang mungkin rosak.",
                "fil": "I-drag para i-rotate. Ipinapakita ng orange mark ang posibleng sira na bahagi.",
                "ur": "گھمانے کے لیے کھینچیں۔ نارنجی نشان ممکنہ خراب جزو دکھاتا ہے۔",
                "bn": "ঘোরাতে টেনে আনুন। কমলা চিহ্ন সম্ভাব্য ত্রুটিপূর্ণ উপাদান দেখায়।",
                "fa": "برای چرخاندن بکشید. علامت نارنجی قطعه احتمالاً معیوب را نشان می‌دهد.",
                "uk": "Перетягніть, щоб обернути. Помаранчева позначка показує ймовірно несправний вузол.",
                "ro": "Trage pentru a roti. Marcajul portocaliu arată componenta probabil defectă.",
                "cs": "Přetažením otočíte. Oranžová značka ukazuje pravděpodobně vadný díl.",
                "sv": "Dra för att rotera. Orange markering visar den troligt felaktiga komponenten.",
                "el": "Σύρετε για περιστροφή. Το πορτοκαλί σημάδι δείχνει το πιθανό ελαττωματικό εξάρτημα.",
                "he": "גררו לסיבוב. הסימון הכתום מציג את הרכיב שככל הנראה פגום.",
                "hu": "Húzza a forgatáshoz. A narancssárga jel a valószínűleg hibás alkatrészt mutatja.",
                "da": "Træk for at dreje. Orange markering viser den sandsynligt defekte komponent.",
                "fi": "Vedä kiertääksesi. Oranssi merkintä näyttää todennäköisesti viallisen osan.",
                "nb": "Dra for å rotere. Oransje merke viser den trolig defekte komponenten.",
                "sk": "Potiahnutím otočíte. Oranžová značka ukazuje pravdepodobne chybný diel.",
                "hr": "Povuci za rotaciju. Narančasta oznaka pokazuje vjerojatno neispravan dio.",
                "bg": "Плъзнете за завъртане. Оранжевият маркер показва вероятния повреден компонент.",
                "sw": "Buruta ili kuzungusha. Alama ya chungwa inaonyesha sehemu inayoweza kuwa na hitilafu.",
                "ca": "Arrossega per girar. La marca taronja mostra el component probablement defectuós.",
            },
            "scene3d.nav": {
                "en": "3D Vehicle",
                "tr": "3D Araç",
                "es": "Vehículo 3D",
                "es-419": "Vehículo 3D",
                "pt-BR": "Veículo 3D",
                "pt-PT": "Veículo 3D",
                "hi": "3D वाहन",
                "id": "Kendaraan 3D",
                "ar": "مركبة ثلاثية الأبعاد",
                "ru": "3D‑автомобиль",
                "de": "3D-Fahrzeug",
                "fr": "Véhicule 3D",
                "ja": "3D車両",
                "ko": "3D 차량",
                "zh-Hans": "3D 车辆",
                "zh-Hant": "3D 車輛",
                "vi": "Xe 3D",
                "th": "ยานพาหนะ 3D",
                "it": "Veicolo 3D",
                "pl": "Pojazd 3D",
                "nl": "3D-voertuig",
                "ms": "Kenderaan 3D",
                "fil": "Sasakyang 3D",
                "ur": "3D گاڑی",
                "bn": "3D যানবাহন",
                "fa": "خودروی سه‌بعدی",
                "uk": "3D‑автомобіль",
                "ro": "Vehicul 3D",
                "cs": "3D vozidlo",
                "sv": "3D-fordon",
                "el": "Όχημα 3D",
                "he": "רכב תלת־ממדי",
                "hu": "3D jármű",
                "da": "3D-køretøj",
                "fi": "3D-ajoneuvo",
                "nb": "3D-bil",
                "sk": "3D vozidlo",
                "hr": "3D vozilo",
                "bg": "3D автомобил",
                "sw": "Gari la 3D",
                "ca": "Vehicle 3D",
            },
        }
    )
    T.update(_community_upload_profile_paywall())


def _community_upload_profile_paywall() -> dict[str, dict[str, str]]:
    return {
        "community.filter": {
            "en": "Filter by DTC",
            "tr": "DTC ile filtrele",
            "es": "Filtrar por DTC",
            "es-419": "Filtrar por DTC",
            "pt-BR": "Filtrar por DTC",
            "pt-PT": "Filtrar por DTC",
            "hi": "DTC से फ़िल्टर करें",
            "id": "Filter menurut DTC",
            "ar": "تصفية حسب DTC",
            "ru": "Фильтр по DTC",
            "de": "Nach DTC filtern",
            "fr": "Filtrer par DTC",
            "ja": "DTCで絞り込み",
            "ko": "DTC로 필터",
            "zh-Hans": "按 DTC 筛选",
            "zh-Hant": "依 DTC 篩選",
            "vi": "Lọc theo DTC",
            "th": "กรองตาม DTC",
            "it": "Filtra per DTC",
            "pl": "Filtruj według DTC",
            "nl": "Filteren op DTC",
            "ms": "Tapis mengikut DTC",
            "fil": "I-filter ayon sa DTC",
            "ur": "DTC سے فلٹر کریں",
            "bn": "DTC দিয়ে ফিল্টার",
            "fa": "فیلتر بر اساس DTC",
            "uk": "Фільтр за DTC",
            "ro": "Filtrează după DTC",
            "cs": "Filtrovat podle DTC",
            "sv": "Filtrera efter DTC",
            "el": "Φίλτρο κατά DTC",
            "he": "סינון לפי DTC",
            "hu": "Szűrés DTC szerint",
            "da": "Filtrer efter DTC",
            "fi": "Suodata DTC:n mukaan",
            "nb": "Filtrer etter DTC",
            "sk": "Filtrovať podľa DTC",
            "hr": "Filtriraj po DTC",
            "bg": "Филтър по DTC",
            "sw": "Chuja kwa DTC",
            "ca": "Filtra per DTC",
        },
        "community.comments": {
            "en": "Comments",
            "tr": "Yorumlar",
            "es": "Comentarios",
            "es-419": "Comentarios",
            "pt-BR": "Comentários",
            "pt-PT": "Comentários",
            "hi": "टिप्पणियाँ",
            "id": "Komentar",
            "ar": "التعليقات",
            "ru": "Комментарии",
            "de": "Kommentare",
            "fr": "Commentaires",
            "ja": "コメント",
            "ko": "댓글",
            "zh-Hans": "评论",
            "zh-Hant": "留言",
            "vi": "Bình luận",
            "th": "ความคิดเห็น",
            "it": "Commenti",
            "pl": "Komentarze",
            "nl": "Reacties",
            "ms": "Komen",
            "fil": "Mga komento",
            "ur": "تبصرے",
            "bn": "মন্তব্য",
            "fa": "نظرات",
            "uk": "Коментарі",
            "ro": "Comentarii",
            "cs": "Komentáře",
            "sv": "Kommentarer",
            "el": "Σχόλια",
            "he": "תגובות",
            "hu": "Hozzászólások",
            "da": "Kommentarer",
            "fi": "Kommentit",
            "nb": "Kommentarer",
            "sk": "Komentáre",
            "hr": "Komentari",
            "bg": "Коментари",
            "sw": "Maoni",
            "ca": "Comentaris",
        },
        "community.comment.placeholder": {
            "en": "Share your fix…",
            "tr": "Çözümünü paylaş…",
            "es": "Comparte tu solución…",
            "es-419": "Comparte tu solución…",
            "pt-BR": "Compartilhe sua correção…",
            "pt-PT": "Partilhe a sua correção…",
            "hi": "अपना समाधान साझा करें…",
            "id": "Bagikan perbaikan Anda…",
            "ar": "شارك إصلاحك…",
            "ru": "Поделитесь своим решением…",
            "de": "Teilen Sie Ihre Lösung…",
            "fr": "Partagez votre solution…",
            "ja": "修理内容を共有…",
            "ko": "해결 방법을 공유하세요…",
            "zh-Hans": "分享你的修复方法…",
            "zh-Hant": "分享你的修復方法…",
            "vi": "Chia sẻ cách sửa của bạn…",
            "th": "แชร์วิธีแก้ของคุณ…",
            "it": "Condividi la tua soluzione…",
            "pl": "Podziel się naprawą…",
            "nl": "Deel je oplossing…",
            "ms": "Kongsi pembaikan anda…",
            "fil": "Ibahagi ang ayos mo…",
            "ur": "اپنا حل شیئر کریں…",
            "bn": "আপনার সমাধান শেয়ার করুন…",
            "fa": "راه‌حل خود را به اشتراک بگذارید…",
            "uk": "Поділіться своїм рішенням…",
            "ro": "Împărtășește reparația ta…",
            "cs": "Sdílejte svou opravu…",
            "sv": "Dela din lösning…",
            "el": "Μοιραστείτε τη λύση σας…",
            "he": "שתפו את התיקון שלכם…",
            "hu": "Ossza meg a javítását…",
            "da": "Del din løsning…",
            "fi": "Jaa korjauksesi…",
            "nb": "Del løsningen din…",
            "sk": "Zdieľajte svoju opravu…",
            "hr": "Podijeli svoje rješenje…",
            "bg": "Споделете поправката си…",
            "sw": "Shiriki suluhisho lako…",
            "ca": "Comparteix la teva solució…",
        },
        "community.comment.send": {
            "en": "Send",
            "tr": "Gönder",
            "es": "Enviar",
            "es-419": "Enviar",
            "pt-BR": "Enviar",
            "pt-PT": "Enviar",
            "hi": "भेजें",
            "id": "Kirim",
            "ar": "إرسال",
            "ru": "Отправить",
            "de": "Senden",
            "fr": "Envoyer",
            "ja": "送信",
            "ko": "보내기",
            "zh-Hans": "发送",
            "zh-Hant": "傳送",
            "vi": "Gửi",
            "th": "ส่ง",
            "it": "Invia",
            "pl": "Wyślij",
            "nl": "Versturen",
            "ms": "Hantar",
            "fil": "Ipadala",
            "ur": "بھیجیں",
            "bn": "পাঠান",
            "fa": "ارسال",
            "uk": "Надіслати",
            "ro": "Trimite",
            "cs": "Odeslat",
            "sv": "Skicka",
            "el": "Αποστολή",
            "he": "שלח",
            "hu": "Küldés",
            "da": "Send",
            "fi": "Lähetä",
            "nb": "Send",
            "sk": "Odoslať",
            "hr": "Pošalji",
            "bg": "Изпрати",
            "sw": "Tuma",
            "ca": "Envia",
        },
        "upload.details": {
            "en": "Details",
            "tr": "Detaylar",
            "es": "Detalles",
            "es-419": "Detalles",
            "pt-BR": "Detalhes",
            "pt-PT": "Detalhes",
            "hi": "विवरण",
            "id": "Detail",
            "ar": "التفاصيل",
            "ru": "Подробности",
            "de": "Details",
            "fr": "Détails",
            "ja": "詳細",
            "ko": "세부정보",
            "zh-Hans": "详细信息",
            "zh-Hant": "詳細資料",
            "vi": "Chi tiết",
            "th": "รายละเอียด",
            "it": "Dettagli",
            "pl": "Szczegóły",
            "nl": "Details",
            "ms": "Butiran",
            "fil": "Mga detalye",
            "ur": "تفصیلات",
            "bn": "বিস্তারিত",
            "fa": "جزئیات",
            "uk": "Деталі",
            "ro": "Detalii",
            "cs": "Podrobnosti",
            "sv": "Detaljer",
            "el": "Λεπτομέρειες",
            "he": "פרטים",
            "hu": "Részletek",
            "da": "Detaljer",
            "fi": "Tiedot",
            "nb": "Detaljer",
            "sk": "Podrobnosti",
            "hr": "Detalji",
            "bg": "Подробности",
            "sw": "Maelezo",
            "ca": "Detalls",
        },
        "upload.title": {
            "en": "Title",
            "tr": "Başlık",
            "es": "Título",
            "es-419": "Título",
            "pt-BR": "Título",
            "pt-PT": "Título",
            "hi": "शीर्षक",
            "id": "Judul",
            "ar": "العنوان",
            "ru": "Заголовок",
            "de": "Titel",
            "fr": "Titre",
            "ja": "タイトル",
            "ko": "제목",
            "zh-Hans": "标题",
            "zh-Hant": "標題",
            "vi": "Tiêu đề",
            "th": "ชื่อเรื่อง",
            "it": "Titolo",
            "pl": "Tytuł",
            "nl": "Titel",
            "ms": "Tajuk",
            "fil": "Pamagat",
            "ur": "عنوان",
            "bn": "শিরোনাম",
            "fa": "عنوان",
            "uk": "Заголовок",
            "ro": "Titlu",
            "cs": "Název",
            "sv": "Titel",
            "el": "Τίτλος",
            "he": "כותרת",
            "hu": "Cím",
            "da": "Titel",
            "fi": "Otsikko",
            "nb": "Tittel",
            "sk": "Názov",
            "hr": "Naslov",
            "bg": "Заглавие",
            "sw": "Kichwa",
            "ca": "Títol",
        },
        "upload.summary": {
            "en": "What fixed it?",
            "tr": "Ne düzeltti?",
            "es": "¿Qué lo solucionó?",
            "es-419": "¿Qué lo solucionó?",
            "pt-BR": "O que resolveu?",
            "pt-PT": "O que resolveu?",
            "hi": "क्या ठीक हुआ?",
            "id": "Apa yang memperbaikinya?",
            "ar": "ما الذي أصلحه؟",
            "ru": "Что помогло?",
            "de": "Was hat geholfen?",
            "fr": "Qu’est-ce qui a résolu le problème ?",
            "ja": "何で直りましたか？",
            "ko": "무엇이 해결했나요?",
            "zh-Hans": "是什么修好的？",
            "zh-Hant": "是什麼修好的？",
            "vi": "Cái gì đã khắc phục?",
            "th": "อะไรทำให้หาย?",
            "it": "Cosa l’ha risolto?",
            "pl": "Co pomogło?",
            "nl": "Wat heeft het opgelost?",
            "ms": "Apa yang membaikinya?",
            "fil": "Ano ang nag-ayos?",
            "ur": "کیا چیز ٹھیک ہوئی؟",
            "bn": "কী ঠিক করেছে?",
            "fa": "چه چیزی درستش کرد؟",
            "uk": "Що допомогло?",
            "ro": "Ce a rezolvat?",
            "cs": "Co to opravilo?",
            "sv": "Vad löste det?",
            "el": "Τι το διόρθωσε;",
            "he": "מה תיקן את זה?",
            "hu": "Mi javította meg?",
            "da": "Hvad løste det?",
            "fi": "Mikä korjasi sen?",
            "nb": "Hva fikset det?",
            "sk": "Čo to opravilo?",
            "hr": "Što ga je popravilo?",
            "bg": "Какво го оправи?",
            "sw": "Nini kilichokitengeneza?",
            "ca": "Què ho ha solucionat?",
        },
        "upload.media": {
            "en": "Media",
            "tr": "Medya",
            "es": "Medios",
            "es-419": "Medios",
            "pt-BR": "Mídia",
            "pt-PT": "Multimédia",
            "hi": "मीडिया",
            "id": "Media",
            "ar": "الوسائط",
            "ru": "Медиа",
            "de": "Medien",
            "fr": "Médias",
            "ja": "メディア",
            "ko": "미디어",
            "zh-Hans": "媒体",
            "zh-Hant": "媒體",
            "vi": "Phương tiện",
            "th": "สื่อ",
            "it": "Media",
            "pl": "Multimedia",
            "nl": "Media",
            "ms": "Media",
            "fil": "Media",
            "ur": "میڈیا",
            "bn": "মিডিয়া",
            "fa": "رسانه",
            "uk": "Медіа",
            "ro": "Media",
            "cs": "Média",
            "sv": "Media",
            "el": "Πολυμέσα",
            "he": "מדיה",
            "hu": "Média",
            "da": "Medier",
            "fi": "Media",
            "nb": "Media",
            "sk": "Médiá",
            "hr": "Mediji",
            "bg": "Медия",
            "sw": "Midia",
            "ca": "Continguts",
        },
        "upload.pick": {
            "en": "Pick a video",
            "tr": "Video seç",
            "es": "Elegir un vídeo",
            "es-419": "Elegir un video",
            "pt-BR": "Escolher um vídeo",
            "pt-PT": "Escolher um vídeo",
            "hi": "वीडियो चुनें",
            "id": "Pilih video",
            "ar": "اختر فيديو",
            "ru": "Выберите видео",
            "de": "Video auswählen",
            "fr": "Choisir une vidéo",
            "ja": "動画を選択",
            "ko": "영상 선택",
            "zh-Hans": "选择视频",
            "zh-Hant": "選擇影片",
            "vi": "Chọn video",
            "th": "เลือกวิดีโอ",
            "it": "Scegli un video",
            "pl": "Wybierz film",
            "nl": "Kies een video",
            "ms": "Pilih video",
            "fil": "Pumili ng video",
            "ur": "ویڈیو منتخب کریں",
            "bn": "ভিডিও বেছে নিন",
            "fa": "یک ویدیو انتخاب کنید",
            "uk": "Виберіть відео",
            "ro": "Alege un videoclip",
            "cs": "Vyberte video",
            "sv": "Välj en video",
            "el": "Επιλέξτε βίντεο",
            "he": "בחרו סרטון",
            "hu": "Válasszon videót",
            "da": "Vælg en video",
            "fi": "Valitse video",
            "nb": "Velg en video",
            "sk": "Vyberte video",
            "hr": "Odaberi videozapis",
            "bg": "Изберете видео",
            "sw": "Chagua video",
            "ca": "Tria un vídeo",
        },
        "upload.submit": {
            "en": "Submit for review",
            "tr": "İncelemeye gönder",
            "es": "Enviar para revisión",
            "es-419": "Enviar para revisión",
            "pt-BR": "Enviar para análise",
            "pt-PT": "Submeter para análise",
            "hi": "समीक्षा के लिए भेजें",
            "id": "Kirim untuk ditinjau",
            "ar": "إرسال للمراجعة",
            "ru": "Отправить на проверку",
            "de": "Zur Prüfung senden",
            "fr": "Soumettre pour examen",
            "ja": "審査に提出",
            "ko": "검토 요청",
            "zh-Hans": "提交审核",
            "zh-Hant": "提交審核",
            "vi": "Gửi để duyệt",
            "th": "ส่งเพื่อตรวจสอบ",
            "it": "Invia per revisione",
            "pl": "Wyślij do weryfikacji",
            "nl": "Indienen ter beoordeling",
            "ms": "Hantar untuk semakan",
            "fil": "Isumite para sa review",
            "ur": "جائزے کے لیے بھیجیں",
            "bn": "পর্যালোচনার জন্য জমা দিন",
            "fa": "ارسال برای بررسی",
            "uk": "Надіслати на перевірку",
            "ro": "Trimite pentru verificare",
            "cs": "Odeslat ke kontrole",
            "sv": "Skicka för granskning",
            "el": "Υποβολή για έλεγχο",
            "he": "שלח לבדיקה",
            "hu": "Beküldés ellenőrzésre",
            "da": "Send til gennemgang",
            "fi": "Lähetä tarkistettavaksi",
            "nb": "Send inn til gjennomgang",
            "sk": "Odoslať na kontrolu",
            "hr": "Pošalji na pregled",
            "bg": "Изпрати за преглед",
            "sw": "Wasilisha kwa ukaguzi",
            "ca": "Envia per a revisió",
        },
        "upload.success": {
            "en": "Uploaded. Pending moderation (admins publish instantly).",
            "tr": "Yüklendi. Moderasyon bekliyor (admin anında yayınlar).",
            "es": "Subido. Pendiente de moderación (los admins publican al instante).",
            "es-419": "Subido. Pendiente de moderación (los admins publican al instante).",
            "pt-BR": "Enviado. Aguardando moderação (admins publicam na hora).",
            "pt-PT": "Carregado. A aguardar moderação (os admins publicam de imediato).",
            "hi": "अपलोड हो गया। मॉडरेशन लंबित (एडमिन तुरंत प्रकाशित करते हैं)।",
            "id": "Diunggah. Menunggu moderasi (admin langsung memublikasikan).",
            "ar": "تم الرفع. بانتظار المراجعة (ينشر المشرفون فورًا).",
            "ru": "Загружено. Ожидает модерации (админы публикуют сразу).",
            "de": "Hochgeladen. Warte auf Moderation (Admins veröffentlichen sofort).",
            "fr": "Importé. En attente de modération (les admins publient immédiatement).",
            "ja": "アップロード済み。審査待ち（管理者は即公開）。",
            "ko": "업로드됨. 검수 대기 중(관리자는 즉시 게시).",
            "zh-Hans": "已上传。等待审核（管理员可立即发布）。",
            "zh-Hant": "已上傳。等待審核（管理員可立即發佈）。",
            "vi": "Đã tải lên. Đang chờ kiểm duyệt (quản trị viên đăng ngay).",
            "th": "อัปโหลดแล้ว รอการตรวจสอบ (แอดมินเผยแพร่ได้ทันที)",
            "it": "Caricato. In attesa di moderazione (gli admin pubblicano subito).",
            "pl": "Przesłano. Oczekuje na moderację (admini publikują od razu).",
            "nl": "Geüpload. Wacht op moderatie (admins publiceren direct).",
            "ms": "Dimuat naik. Menunggu penyederhanaan (admin terbitkan serta-merta).",
            "fil": "Na-upload. Nakabinbin ang moderation (agad magpo-publish ang admin).",
            "ur": "اپ لوڈ ہو گیا۔ ماڈریشن زیر التوا (ایڈمنز فوری شائع کرتے ہیں)۔",
            "bn": "আপলোড হয়েছে। মডারেশন অপেক্ষমাণ (অ্যাডমিন সাথে সাথে প্রকাশ করে)।",
            "fa": "آپلود شد. در انتظار بررسی (مدیران فوری منتشر می‌کنند).",
            "uk": "Завантажено. Очікує модерації (адміни публікують одразу).",
            "ro": "Încărcat. Așteaptă moderare (adminii publică imediat).",
            "cs": "Nahráno. Čeká na moderaci (admini publikují ihned).",
            "sv": "Uppladdat. Väntar på moderering (admins publicerar direkt).",
            "el": "Μεταφορτώθηκε. Εκκρεμεί έλεγχος (οι διαχειριστές δημοσιεύουν αμέσως).",
            "he": "הועלה. ממתין לאישור (מנהלים מפרסמים מיד).",
            "hu": "Feltöltve. Moderálásra vár (az adminok azonnal közzéteszik).",
            "da": "Uploadet. Afventer moderation (admins udgiver med det samme).",
            "fi": "Ladattu. Odottaa moderointia (ylläpitäjät julkaisevat heti).",
            "nb": "Lastet opp. Venter på moderering (admin publiserer med en gang).",
            "sk": "Nahrané. Čaká na moderáciu (admini publikujú ihneď).",
            "hr": "Učitano. Čeka moderaciju (admini objavljuju odmah).",
            "bg": "Качено. Чака модерация (админите публикуват веднага).",
            "sw": "Imepakuliwa. Inasubiri ukaguzi (wasimamizi huchapisha mara moja).",
            "ca": "Pujat. Pendent de moderació (els admins publiquen a l’instant).",
        },
        "upload.error.title": {
            "en": "Title is required.",
            "tr": "Başlık gerekli.",
            "es": "El título es obligatorio.",
            "es-419": "El título es obligatorio.",
            "pt-BR": "O título é obrigatório.",
            "pt-PT": "O título é obrigatório.",
            "hi": "शीर्षक आवश्यक है।",
            "id": "Judul wajib diisi.",
            "ar": "العنوان مطلوب.",
            "ru": "Заголовок обязателен.",
            "de": "Titel ist erforderlich.",
            "fr": "Le titre est obligatoire.",
            "ja": "タイトルは必須です。",
            "ko": "제목은 필수입니다.",
            "zh-Hans": "标题为必填项。",
            "zh-Hant": "標題為必填。",
            "vi": "Tiêu đề là bắt buộc.",
            "th": "ต้องระบุชื่อเรื่อง",
            "it": "Il titolo è obbligatorio.",
            "pl": "Tytuł jest wymagany.",
            "nl": "Titel is verplicht.",
            "ms": "Tajuk diperlukan.",
            "fil": "Kailangan ang pamagat.",
            "ur": "عنوان ضروری ہے۔",
            "bn": "শিরোনাম প্রয়োজন।",
            "fa": "عنوان الزامی است.",
            "uk": "Заголовок обов’язковий.",
            "ro": "Titlul este obligatoriu.",
            "cs": "Název je povinný.",
            "sv": "Titel krävs.",
            "el": "Ο τίτλος είναι υποχρεωτικός.",
            "he": "נדרשת כותרת.",
            "hu": "A cím kötelező.",
            "da": "Titel er påkrævet.",
            "fi": "Otsikko on pakollinen.",
            "nb": "Tittel er påkrevd.",
            "sk": "Názov je povinný.",
            "hr": "Naslov je obavezan.",
            "bg": "Заглавието е задължително.",
            "sw": "Kichwa kinahitajika.",
            "ca": "El títol és obligatori.",
        },
        "upload.quota %lld": {
            "en": "%lld uploads left this month",
            "tr": "Bu ay %lld yükleme hakkın kaldı",
            "es": "Te quedan %lld subidas este mes",
            "es-419": "Te quedan %lld subidas este mes",
            "pt-BR": "%lld envios restantes neste mês",
            "pt-PT": "%lld carregamentos restantes este mês",
            "hi": "इस महीने %lld अपलोड शेष",
            "id": "%lld unggahan tersisa bulan ini",
            "ar": "يتبقى %lld رفعًا هذا الشهر",
            "ru": "Осталось %lld загрузок в этом месяце",
            "de": "Noch %lld Uploads diesen Monat",
            "fr": "%lld imports restants ce mois-ci",
            "ja": "今月の残りアップロード：%lld",
            "ko": "이번 달 업로드 %lld회 남음",
            "zh-Hans": "本月剩余 %lld 次上传",
            "zh-Hant": "本月剩餘 %lld 次上傳",
            "vi": "Còn %lld lượt tải lên trong tháng này",
            "th": "เหลือการอัปโหลด %lld ครั้งในเดือนนี้",
            "it": "%lld caricamenti rimasti questo mese",
            "pl": "Pozostało %lld przesłań w tym miesiącu",
            "nl": "Nog %lld uploads deze maand",
            "ms": "%lld muat naik lagi bulan ini",
            "fil": "%lld upload pa ang natitira ngayong buwan",
            "ur": "اس مہینے %lld اپ لوڈ باقی",
            "bn": "এই মাসে %lld আপলোড বাকি",
            "fa": "%lld آپلود باقی‌مانده در این ماه",
            "uk": "Залишилось %lld завантажень цього місяця",
            "ro": "%lld încărcări rămase luna aceasta",
            "cs": "Tento měsíc zbývá %lld nahrání",
            "sv": "%lld uppladdningar kvar den här månaden",
            "el": "Απομένουν %lld μεταφορτώσεις αυτόν τον μήνα",
            "he": "נותרו %lld העלאות החודש",
            "hu": "Ebben a hónapban %lld feltöltés van hátra",
            "da": "%lld uploads tilbage denne måned",
            "fi": "%lld latausta jäljellä tässä kuussa",
            "nb": "%lld opplastinger igjen denne måneden",
            "sk": "Tento mesiac zostáva %lld nahraní",
            "hr": "Preostalo %lld učitavanja ovog mjeseca",
            "bg": "Остават %lld качвания този месец",
            "sw": "Upakiaji %lld umebaki mwezi huu",
            "ca": "Et queden %lld pujades aquest mes",
        },
        "%lld uploads left this month": {
            "en": "%lld uploads left this month",
            "tr": "Bu ay %lld yükleme hakkın kaldı",
            "es": "Te quedan %lld subidas este mes",
            "es-419": "Te quedan %lld subidas este mes",
            "pt-BR": "%lld envios restantes neste mês",
            "pt-PT": "%lld carregamentos restantes este mês",
            "hi": "इस महीने %lld अपलोड शेष",
            "id": "%lld unggahan tersisa bulan ini",
            "ar": "يتبقى %lld رفعًا هذا الشهر",
            "ru": "Осталось %lld загрузок в этом месяце",
            "de": "Noch %lld Uploads diesen Monat",
            "fr": "%lld imports restants ce mois-ci",
            "ja": "今月の残りアップロード：%lld",
            "ko": "이번 달 업로드 %lld회 남음",
            "zh-Hans": "本月剩余 %lld 次上传",
            "zh-Hant": "本月剩餘 %lld 次上傳",
            "vi": "Còn %lld lượt tải lên trong tháng này",
            "th": "เหลือการอัปโหลด %lld ครั้งในเดือนนี้",
            "it": "%lld caricamenti rimasti questo mese",
            "pl": "Pozostało %lld przesłań w tym miesiącu",
            "nl": "Nog %lld uploads deze maand",
            "ms": "%lld muat naik lagi bulan ini",
            "fil": "%lld upload pa ang natitira ngayong buwan",
            "ur": "اس مہینے %lld اپ لوڈ باقی",
            "bn": "এই মাসে %lld আপলোড বাকি",
            "fa": "%lld آپلود باقی‌مانده در این ماه",
            "uk": "Залишилось %lld завантажень цього місяця",
            "ro": "%lld încărcări rămase luna aceasta",
            "cs": "Tento měsíc zbývá %lld nahrání",
            "sv": "%lld uppladdningar kvar den här månaden",
            "el": "Απομένουν %lld μεταφορτώσεις αυτόν τον μήνα",
            "he": "נותרו %lld העלאות החודש",
            "hu": "Ebben a hónapban %lld feltöltés van hátra",
            "da": "%lld uploads tilbage denne måned",
            "fi": "%lld latausta jäljellä tässä kuussa",
            "nb": "%lld opplastinger igjen denne måneden",
            "sk": "Tento mesiac zostáva %lld nahraní",
            "hr": "Preostalo %lld učitavanja ovog mjeseca",
            "bg": "Остават %lld качвания този месец",
            "sw": "Upakiaji %lld umebaki mwezi huu",
            "ca": "Et queden %lld pujades aquest mes",
        },
        "profile.subscription": {
            "en": "Subscription",
            "tr": "Abonelik",
            "es": "Suscripción",
            "es-419": "Suscripción",
            "pt-BR": "Assinatura",
            "pt-PT": "Subscrição",
            "hi": "सदस्यता",
            "id": "Langganan",
            "ar": "الاشتراك",
            "ru": "Подписка",
            "de": "Abonnement",
            "fr": "Abonnement",
            "ja": "サブスクリプション",
            "ko": "구독",
            "zh-Hans": "订阅",
            "zh-Hant": "訂閱",
            "vi": "Thuê bao",
            "th": "การสมัครสมาชิก",
            "it": "Abbonamento",
            "pl": "Subskrypcja",
            "nl": "Abonnement",
            "ms": "Langganan",
            "fil": "Subscription",
            "ur": "سبسکرپشن",
            "bn": "সাবস্ক্রিপশন",
            "fa": "اشتراک",
            "uk": "Підписка",
            "ro": "Abonament",
            "cs": "Předplatné",
            "sv": "Prenumeration",
            "el": "Συνδρομή",
            "he": "מנוי",
            "hu": "Előfizetés",
            "da": "Abonnement",
            "fi": "Tilaus",
            "nb": "Abonnement",
            "sk": "Predplatné",
            "hr": "Pretplata",
            "bg": "Абонамент",
            "sw": "Usajili",
            "ca": "Subscripció",
        },
        "profile.plan": {
            "en": "Plan",
            "tr": "Plan",
            "es": "Plan",
            "es-419": "Plan",
            "pt-BR": "Plano",
            "pt-PT": "Plano",
            "hi": "योजना",
            "id": "Paket",
            "ar": "الخطة",
            "ru": "Тариф",
            "de": "Tarif",
            "fr": "Offre",
            "ja": "プラン",
            "ko": "플랜",
            "zh-Hans": "方案",
            "zh-Hant": "方案",
            "vi": "Gói",
            "th": "แผน",
            "it": "Piano",
            "pl": "Plan",
            "nl": "Abonnement",
            "ms": "Pelan",
            "fil": "Plan",
            "ur": "پلان",
            "bn": "প্ল্যান",
            "fa": "طرح",
            "uk": "Тариф",
            "ro": "Plan",
            "cs": "Tarif",
            "sv": "Plan",
            "el": "Πλάνο",
            "he": "תוכנית",
            "hu": "Csomag",
            "da": "Plan",
            "fi": "Paketti",
            "nb": "Plan",
            "sk": "Tarif",
            "hr": "Plan",
            "bg": "План",
            "sw": "Mpango",
            "ca": "Pla",
        },
        "profile.plan.pro": {
            "en": "Pro",
            "tr": "Pro",
            "es": "Pro",
            "es-419": "Pro",
            "pt-BR": "Pro",
            "pt-PT": "Pro",
            "hi": "Pro",
            "id": "Pro",
            "ar": "Pro",
            "ru": "Pro",
            "de": "Pro",
            "fr": "Pro",
            "ja": "Pro",
            "ko": "Pro",
            "zh-Hans": "Pro",
            "zh-Hant": "Pro",
            "vi": "Pro",
            "th": "Pro",
            "it": "Pro",
            "pl": "Pro",
            "nl": "Pro",
            "ms": "Pro",
            "fil": "Pro",
            "ur": "Pro",
            "bn": "Pro",
            "fa": "Pro",
            "uk": "Pro",
            "ro": "Pro",
            "cs": "Pro",
            "sv": "Pro",
            "el": "Pro",
            "he": "Pro",
            "hu": "Pro",
            "da": "Pro",
            "fi": "Pro",
            "nb": "Pro",
            "sk": "Pro",
            "hr": "Pro",
            "bg": "Pro",
            "sw": "Pro",
            "ca": "Pro",
        },
        "profile.plan.free": {
            "en": "Free",
            "tr": "Ücretsiz",
            "es": "Gratis",
            "es-419": "Gratis",
            "pt-BR": "Grátis",
            "pt-PT": "Grátis",
            "hi": "मुफ़्त",
            "id": "Gratis",
            "ar": "مجاني",
            "ru": "Бесплатно",
            "de": "Kostenlos",
            "fr": "Gratuit",
            "ja": "無料",
            "ko": "무료",
            "zh-Hans": "免费",
            "zh-Hant": "免費",
            "vi": "Miễn phí",
            "th": "ฟรี",
            "it": "Gratis",
            "pl": "Bezpłatny",
            "nl": "Gratis",
            "ms": "Percuma",
            "fil": "Libre",
            "ur": "مفت",
            "bn": "বিনামূল্যে",
            "fa": "رایگان",
            "uk": "Безкоштовно",
            "ro": "Gratuit",
            "cs": "Zdarma",
            "sv": "Gratis",
            "el": "Δωρεάν",
            "he": "חינם",
            "hu": "Ingyenes",
            "da": "Gratis",
            "fi": "Ilmainen",
            "nb": "Gratis",
            "sk": "Zadarmo",
            "hr": "Besplatno",
            "bg": "Безплатно",
            "sw": "Bure",
            "ca": "Gratuït",
        },
        "profile.upgrade": {
            "en": "Upgrade to Pro",
            "tr": "Pro’ya geç",
            "es": "Pasar a Pro",
            "es-419": "Pasar a Pro",
            "pt-BR": "Assinar o Pro",
            "pt-PT": "Atualizar para Pro",
            "hi": "Pro में अपग्रेड करें",
            "id": "Upgrade ke Pro",
            "ar": "الترقية إلى Pro",
            "ru": "Перейти на Pro",
            "de": "Auf Pro upgraden",
            "fr": "Passer à Pro",
            "ja": "Proにアップグレード",
            "ko": "Pro로 업그레이드",
            "zh-Hans": "升级到 Pro",
            "zh-Hant": "升級至 Pro",
            "vi": "Nâng cấp lên Pro",
            "th": "อัปเกรดเป็น Pro",
            "it": "Passa a Pro",
            "pl": "Ulepsz do Pro",
            "nl": "Upgraden naar Pro",
            "ms": "Naik taraf ke Pro",
            "fil": "Mag-upgrade sa Pro",
            "ur": "Pro میں اپ گریڈ کریں",
            "bn": "Pro-তে আপগ্রেড করুন",
            "fa": "ارتقاء به Pro",
            "uk": "Перейти на Pro",
            "ro": "Treci la Pro",
            "cs": "Přejít na Pro",
            "sv": "Uppgradera till Pro",
            "el": "Αναβάθμιση σε Pro",
            "he": "שדרוג ל‑Pro",
            "hu": "Váltás Pro-ra",
            "da": "Opgrader til Pro",
            "fi": "Päivitä Prohon",
            "nb": "Oppgrader til Pro",
            "sk": "Prejsť na Pro",
            "hr": "Nadogradi na Pro",
            "bg": "Надградете до Pro",
            "sw": "Boresha hadi Pro",
            "ca": "Actualitza a Pro",
        },
        "profile.myVideos": {
            "en": "My videos",
            "tr": "Videolarım",
            "es": "Mis vídeos",
            "es-419": "Mis videos",
            "pt-BR": "Meus vídeos",
            "pt-PT": "Os meus vídeos",
            "hi": "मेरे वीडियो",
            "id": "Video saya",
            "ar": "فيديوهاتي",
            "ru": "Мои видео",
            "de": "Meine Videos",
            "fr": "Mes vidéos",
            "ja": "自分の動画",
            "ko": "내 영상",
            "zh-Hans": "我的视频",
            "zh-Hant": "我的影片",
            "vi": "Video của tôi",
            "th": "วิดีโอของฉัน",
            "it": "I miei video",
            "pl": "Moje filmy",
            "nl": "Mijn video’s",
            "ms": "Video saya",
            "fil": "Mga video ko",
            "ur": "میری ویڈیوز",
            "bn": "আমার ভিডিও",
            "fa": "ویدیوهای من",
            "uk": "Мої відео",
            "ro": "Videoclipurile mele",
            "cs": "Moje videa",
            "sv": "Mina videor",
            "el": "Τα βίντεό μου",
            "he": "הסרטונים שלי",
            "hu": "Saját videóim",
            "da": "Mine videoer",
            "fi": "Omat videot",
            "nb": "Mine videoer",
            "sk": "Moje videá",
            "hr": "Moji videozapisi",
            "bg": "Моите видеа",
            "sw": "Video zangu",
            "ca": "Els meus vídeos",
        },
        "profile.myVideos.empty": {
            "en": "No uploads yet.",
            "tr": "Henüz yükleme yok.",
            "es": "Aún no hay subidas.",
            "es-419": "Aún no hay subidas.",
            "pt-BR": "Ainda não há envios.",
            "pt-PT": "Ainda não há carregamentos.",
            "hi": "अभी कोई अपलोड नहीं।",
            "id": "Belum ada unggahan.",
            "ar": "لا توجد عمليات رفع بعد.",
            "ru": "Пока нет загрузок.",
            "de": "Noch keine Uploads.",
            "fr": "Aucun import pour le moment.",
            "ja": "まだアップロードがありません。",
            "ko": "아직 업로드가 없습니다.",
            "zh-Hans": "暂无上传。",
            "zh-Hant": "尚無上傳。",
            "vi": "Chưa có nội dung tải lên.",
            "th": "ยังไม่มีการอัปโหลด",
            "it": "Nessun caricamento ancora.",
            "pl": "Brak przesłań.",
            "nl": "Nog geen uploads.",
            "ms": "Belum ada muat naik.",
            "fil": "Wala pang upload.",
            "ur": "ابھی کوئی اپ لوڈ نہیں۔",
            "bn": "এখনও কোনো আপলোড নেই।",
            "fa": "هنوز آپلودی نیست.",
            "uk": "Поки немає завантажень.",
            "ro": "Nicio încărcare încă.",
            "cs": "Zatím žádná nahrání.",
            "sv": "Inga uppladdningar ännu.",
            "el": "Δεν υπάρχουν ακόμη μεταφορτώσεις.",
            "he": "עדיין אין העלאות.",
            "hu": "Még nincsenek feltöltések.",
            "da": "Ingen uploads endnu.",
            "fi": "Ei vielä latauksia.",
            "nb": "Ingen opplastinger ennå.",
            "sk": "Zatiaľ žiadne nahratia.",
            "hr": "Još nema učitavanja.",
            "bg": "Все още няма качвания.",
            "sw": "Bado hakuna upakiaji.",
            "ca": "Encara no hi ha pujades.",
        },
        "profile.signOut": {
            "en": "Sign out",
            "tr": "Çıkış yap",
            "es": "Cerrar sesión",
            "es-419": "Cerrar sesión",
            "pt-BR": "Sair",
            "pt-PT": "Terminar sessão",
            "hi": "साइन आउट",
            "id": "Keluar",
            "ar": "تسجيل الخروج",
            "ru": "Выйти",
            "de": "Abmelden",
            "fr": "Se déconnecter",
            "ja": "サインアウト",
            "ko": "로그아웃",
            "zh-Hans": "退出登录",
            "zh-Hant": "登出",
            "vi": "Đăng xuất",
            "th": "ออกจากระบบ",
            "it": "Esci",
            "pl": "Wyloguj",
            "nl": "Afmelden",
            "ms": "Log keluar",
            "fil": "Mag-sign out",
            "ur": "سائن آؤٹ",
            "bn": "সাইন আউট",
            "fa": "خروج",
            "uk": "Вийти",
            "ro": "Deconectare",
            "cs": "Odhlásit se",
            "sv": "Logga ut",
            "el": "Αποσύνδεση",
            "he": "התנתקות",
            "hu": "Kijelentkezés",
            "da": "Log ud",
            "fi": "Kirjaudu ulos",
            "nb": "Logg ut",
            "sk": "Odhlásiť sa",
            "hr": "Odjava",
            "bg": "Изход",
            "sw": "Toka",
            "ca": "Tanca la sessió",
        },
        "paywall.subtitle": {
            "en": "Unlock 3D part highlight, higher video quota, and repair history.",
            "tr": "3D parça vurgusu, yüksek video kotası ve tamir geçmişini aç.",
            "es": "Desbloquea el resaltado 3D de piezas, más cuota de vídeo e historial de reparaciones.",
            "es-419": "Desbloquea el resaltado 3D de piezas, más cuota de video e historial de reparaciones.",
            "pt-BR": "Desbloqueie destaque 3D de peças, mais cota de vídeo e histórico de reparos.",
            "pt-PT": "Desbloqueie o destaque 3D de peças, mais quota de vídeo e histórico de reparações.",
            "hi": "3D पार्ट हाइलाइट, अधिक वीडियो कोटा और मरम्मत इतिहास अनलॉक करें।",
            "id": "Buka sorotan suku cadang 3D, kuota video lebih tinggi, dan riwayat perbaikan.",
            "ar": "افتح تمييز القطع ثلاثي الأبعاد وحصة فيديو أعلى وسجل الإصلاحات.",
            "ru": "Откройте 3D‑подсветку деталей, больший лимит видео и историю ремонтов.",
            "de": "Schalten Sie 3D-Teilmarkierung, höheres Videokontingent und Reparaturverlauf frei.",
            "fr": "Débloquez la mise en évidence 3D, un quota vidéo plus élevé et l’historique des réparations.",
            "ja": "3D部品ハイライト、動画枠の拡大、修理履歴を解除。",
            "ko": "3D 부품 하이라이트, 더 많은 영상 할당량, 수리 기록을 잠금 해제하세요.",
            "zh-Hans": "解锁 3D 零件高亮、更高视频配额和维修历史。",
            "zh-Hant": "解鎖 3D 零件醒目、更高影片配額與維修紀錄。",
            "vi": "Mở khóa tô sáng phụ tùng 3D, hạn mức video cao hơn và lịch sử sửa chữa.",
            "th": "ปลดล็อกไฮไลต์อะไหล่ 3D โควตาวิดีโอสูงขึ้น และประวัติการซ่อม",
            "it": "Sblocca evidenziazione 3D, quota video maggiore e cronologia riparazioni.",
            "pl": "Odblokuj podświetlenie części 3D, wyższy limit filmów i historię napraw.",
            "nl": "Ontgrendel 3D-onderdeelmarkering, hogere videocota en reparatiegeschiedenis.",
            "ms": "Buka kunci sorotan bahagian 3D, kuota video lebih tinggi dan sejarah pembaikan.",
            "fil": "I-unlock ang 3D part highlight, mas mataas na video quota, at repair history.",
            "ur": "3D پرزہ ہائی لائٹ، زیادہ ویڈیو کوٹہ اور مرمت کی تاریخ ان لاک کریں۔",
            "bn": "3D যন্ত্রাংশ হাইলাইট, বেশি ভিডিও কোটা ও মেরামত ইতিহাস আনলক করুন।",
            "fa": "برجسته‌سازی سه‌بعدی قطعه، سهمیه ویدیوی بیشتر و تاریخچه تعمیر را باز کنید.",
            "uk": "Відкрийте 3D‑підсвічування деталей, більший ліміт відео та історію ремонтів.",
            "ro": "Deblochează evidențierea 3D a pieselor, cotă video mai mare și istoricul reparațiilor.",
            "cs": "Odemkněte zvýraznění dílu ve 3D, vyšší kvótu videí a historii oprav.",
            "sv": "Lås upp 3D-markering, högre videokvot och reparationshistorik.",
            "el": "Ξεκλειδώστε επισήμανση εξαρτήματος 3D, μεγαλύτερο όριο βίντεο και ιστορικό επισκευών.",
            "he": "פתחו הדגשת חלקים בתלת־ממד, מכסת סרטונים גבוהה יותר והיסטוריית תיקונים.",
            "hu": "Oldja fel a 3D alkatrész-kiemelést, a magasabb videókvótát és a javítási előzményeket.",
            "da": "Lås 3D-delmarkering, højere videokvote og reparationshistorik op.",
            "fi": "Avaa 3D-osakorostus, suurempi videokiintiö ja korjaushistoria.",
            "nb": "Lås opp 3D-delmarkering, høyere videokvote og reparasjonshistorikk.",
            "sk": "Odomknite zvýraznenie dielu v 3D, vyššiu kvótu videí a históriu opráv.",
            "hr": "Otključaj 3D isticanje dijela, veću video kvotu i povijest popravaka.",
            "bg": "Отключете 3D маркиране на части, по-голяма видео квота и история на ремонти.",
            "sw": "Fungua kuangazia sehemu kwa 3D, kiasi kikubwa cha video, na historia ya ukarabati.",
            "ca": "Desbloqueja el ressaltat 3D de peces, més quota de vídeo i l’historial de reparacions.",
        },
        "paywall.benefit.3d": {
            "en": "Interactive 3D fault localization",
            "tr": "İnteraktif 3D arıza konumlandırma",
            "es": "Localización interactiva de fallos en 3D",
            "es-419": "Localización interactiva de fallas en 3D",
            "pt-BR": "Localização interativa de falhas em 3D",
            "pt-PT": "Localização interativa de avarias em 3D",
            "hi": "इंटरैक्टिव 3D दोष स्थान निर्धारण",
            "id": "Lokalisasi kesalahan 3D interaktif",
            "ar": "تحديد موقع العطل تفاعليًا بتقنية ثلاثية الأبعاد",
            "ru": "Интерактивная 3D‑локализация неисправности",
            "de": "Interaktive 3D-Fehlerlokalisierung",
            "fr": "Localisation interactive des défauts en 3D",
            "ja": "インタラクティブな3D故障位置表示",
            "ko": "인터랙티브 3D 고장 위치 표시",
            "zh-Hans": "交互式 3D 故障定位",
            "zh-Hant": "互動式 3D 故障定位",
            "vi": "Định vị lỗi 3D tương tác",
            "th": "ระบุตำแหน่งความผิดปกติแบบอินเทอร์แอคทีฟ 3D",
            "it": "Localizzazione interattiva dei guasti in 3D",
            "pl": "Interaktywna lokalizacja usterki w 3D",
            "nl": "Interactieve 3D-storingslokalisatie",
            "ms": "Penyetempatan kerosakan 3D interaktif",
            "fil": "Interactive na 3D fault localization",
            "ur": "انٹرایکٹو 3D خرابی مقام تعین",
            "bn": "ইন্টারঅ্যাকটিভ 3D ত্রুটি স্থাননির্ধারণ",
            "fa": "جانمایی تعاملی خطای سه‌بعدی",
            "uk": "Інтерактивна 3D‑локалізація несправності",
            "ro": "Localizare interactivă a defectelor în 3D",
            "cs": "Interaktivní lokalizace závady ve 3D",
            "sv": "Interaktiv 3D-fellokalisering",
            "el": "Διαδραστικός εντοπισμός βλάβης σε 3D",
            "he": "איתור תקלות אינטראקטיבי בתלת־ממד",
            "hu": "Interaktív 3D hibameghatározás",
            "da": "Interaktiv 3D-fejlplacering",
            "fi": "Interaktiivinen 3D-vian paikannus",
            "nb": "Interaktiv 3D-feillokalisering",
            "sk": "Interaktívna lokalizácia poruchy v 3D",
            "hr": "Interaktivna 3D lokalizacija kvara",
            "bg": "Интерактивна 3D локализация на повредата",
            "sw": "Upataji wa mahali pa hitilafu kwa 3D ya kuingiliana",
            "ca": "Localització interactiva d’avaries en 3D",
        },
        "paywall.benefit.video": {
            "en": "Up to 30 community uploads / month",
            "tr": "Ayda 30’a kadar topluluk videosu",
            "es": "Hasta 30 subidas a la comunidad / mes",
            "es-419": "Hasta 30 subidas a la comunidad / mes",
            "pt-BR": "Até 30 envios à comunidade / mês",
            "pt-PT": "Até 30 carregamentos para a comunidade / mês",
            "hi": "प्रति माह 30 तक समुदाय अपलोड",
            "id": "Hingga 30 unggahan komunitas / bulan",
            "ar": "حتى 30 رفعًا للمجتمع شهريًا",
            "ru": "До 30 загрузок в сообщество / месяц",
            "de": "Bis zu 30 Community-Uploads / Monat",
            "fr": "Jusqu’à 30 imports communauté / mois",
            "ja": "コミュニティ投稿最大30件／月",
            "ko": "월 최대 30회 커뮤니티 업로드",
            "zh-Hans": "每月最多 30 次社区上传",
            "zh-Hant": "每月最多 30 次社群上傳",
            "vi": "Tối đa 30 lần tải lên cộng đồng / tháng",
            "th": "อัปโหลดชุมชนได้สูงสุด 30 ครั้ง/เดือน",
            "it": "Fino a 30 caricamenti community / mese",
            "pl": "Do 30 przesłań społeczności / miesiąc",
            "nl": "Tot 30 community-uploads / maand",
            "ms": "Sehingga 30 muat naik komuniti / bulan",
            "fil": "Hanggang 30 community upload / buwan",
            "ur": "ماہانہ 30 تک کمیونٹی اپ لوڈ",
            "bn": "প্রতি মাসে সর্বোচ্চ ৩০টি কমিউনিটি আপলোড",
            "fa": "تا ۳۰ آپلود انجمن در ماه",
            "uk": "До 30 завантажень у спільноту / місяць",
            "ro": "Până la 30 de încărcări în comunitate / lună",
            "cs": "Až 30 nahrání do komunity / měsíc",
            "sv": "Upp till 30 communityuppladdningar / månad",
            "el": "Έως 30 μεταφορτώσεις κοινότητας / μήνα",
            "he": "עד 30 העלאות לקהילה בחודש",
            "hu": "Havonta akár 30 közösségi feltöltés",
            "da": "Op til 30 fællesskabuploads / måned",
            "fi": "Enintään 30 yhteisölatausta / kk",
            "nb": "Opptil 30 fellesskapsopplastinger / måned",
            "sk": "Až 30 nahraní do komunity / mesiac",
            "hr": "Do 30 učitavanja u zajednicu / mjesec",
            "bg": "До 30 качвания в общността / месец",
            "sw": "Hadi upakiaji 30 wa jumuiya / mwezi",
            "ca": "Fins a 30 pujades a la comunitat / mes",
        },
        "paywall.benefit.history": {
            "en": "Unlimited diagnosis history",
            "tr": "Sınırsız teşhis geçmişi",
            "es": "Historial de diagnósticos ilimitado",
            "es-419": "Historial de diagnósticos ilimitado",
            "pt-BR": "Histórico de diagnósticos ilimitado",
            "pt-PT": "Histórico de diagnósticos ilimitado",
            "hi": "असीमित निदान इतिहास",
            "id": "Riwayat diagnosis tanpa batas",
            "ar": "سجل تشخيص غير محدود",
            "ru": "Неограниченная история диагностик",
            "de": "Unbegrenzter Diagnoseverlauf",
            "fr": "Historique de diagnostics illimité",
            "ja": "診断履歴無制限",
            "ko": "무제한 진단 기록",
            "zh-Hans": "无限诊断历史",
            "zh-Hant": "無限診斷紀錄",
            "vi": "Lịch sử chẩn đoán không giới hạn",
            "th": "ประวัติการวินิจฉัยไม่จำกัด",
            "it": "Cronologia diagnosi illimitata",
            "pl": "Nieograniczona historia diagnostyki",
            "nl": "Onbeperkte diagnose-geschiedenis",
            "ms": "Sejarah diagnosis tanpa had",
            "fil": "Walang limitasyong diagnosis history",
            "ur": "لامحدود تشخیص کی تاریخ",
            "bn": "সীমাহীন নির্ণয় ইতিহাস",
            "fa": "تاریخچه تشخیص نامحدود",
            "uk": "Необмежена історія діагностик",
            "ro": "Istoric de diagnostic nelimitat",
            "cs": "Neomezená historie diagnostiky",
            "sv": "Obegränsad diagnoshistorik",
            "el": "Απεριόριστο ιστορικό διαγνώσεων",
            "he": "היסטוריית אבחון ללא הגבלה",
            "hu": "Korlátlan diagnóziselőzmény",
            "da": "Ubegrænset diagnosehistorik",
            "fi": "Rajoittamaton diagnoosihistoria",
            "nb": "Ubegrenset diagnosehistorikk",
            "sk": "Neobmedzená história diagnostiky",
            "hr": "Neograničena povijest dijagnostike",
            "bg": "Неограничена история на диагностиките",
            "sw": "Historia ya utambuzi isiyo na kikomo",
            "ca": "Historial de diagnòstics il·limitat",
        },
        "paywall.demoUnlock": {
            "en": "Unlock Pro (Demo)",
            "tr": "Pro’yu aç (Demo)",
            "es": "Desbloquear Pro (Demo)",
            "es-419": "Desbloquear Pro (Demo)",
            "pt-BR": "Desbloquear Pro (Demo)",
            "pt-PT": "Desbloquear Pro (Demo)",
            "hi": "Pro अनलॉक करें (डेमो)",
            "id": "Buka Pro (Demo)",
            "ar": "فتح Pro (تجريبي)",
            "ru": "Открыть Pro (демо)",
            "de": "Pro freischalten (Demo)",
            "fr": "Débloquer Pro (Démo)",
            "ja": "Proを解除（デモ）",
            "ko": "Pro 잠금 해제(데모)",
            "zh-Hans": "解锁 Pro（演示）",
            "zh-Hant": "解鎖 Pro（示範）",
            "vi": "Mở khóa Pro (Demo)",
            "th": "ปลดล็อก Pro (เดโม)",
            "it": "Sblocca Pro (Demo)",
            "pl": "Odblokuj Pro (Demo)",
            "nl": "Pro ontgrendelen (Demo)",
            "ms": "Buka kunci Pro (Demo)",
            "fil": "I-unlock ang Pro (Demo)",
            "ur": "Pro ان لاک کریں (ڈیمو)",
            "bn": "Pro আনলক করুন (ডেমো)",
            "fa": "باز کردن Pro (آزمایشی)",
            "uk": "Відкрити Pro (демо)",
            "ro": "Deblochează Pro (Demo)",
            "cs": "Odemknout Pro (Demo)",
            "sv": "Lås upp Pro (Demo)",
            "el": "Ξεκλείδωμα Pro (Demo)",
            "he": "פתיחת Pro (הדגמה)",
            "hu": "Pro feloldása (Demó)",
            "da": "Lås Pro op (Demo)",
            "fi": "Avaa Pro (Demo)",
            "nb": "Lås opp Pro (Demo)",
            "sk": "Odomknúť Pro (Demo)",
            "hr": "Otključaj Pro (Demo)",
            "bg": "Отключи Pro (Демо)",
            "sw": "Fungua Pro (Demo)",
            "ca": "Desbloqueja Pro (Demostració)",
        },
        "paywall.restore": {
            "en": "Restore purchases",
            "tr": "Satın alımları geri yükle",
            "es": "Restaurar compras",
            "es-419": "Restaurar compras",
            "pt-BR": "Restaurar compras",
            "pt-PT": "Restaurar compras",
            "hi": "खरीदारी पुनर्स्थापित करें",
            "id": "Pulihkan pembelian",
            "ar": "استعادة المشتريات",
            "ru": "Восстановить покупки",
            "de": "Käufe wiederherstellen",
            "fr": "Restaurer les achats",
            "ja": "購入を復元",
            "ko": "구입 항목 복원",
            "zh-Hans": "恢复购买",
            "zh-Hant": "回復購買項目",
            "vi": "Khôi phục giao dịch mua",
            "th": "กู้คืนการซื้อ",
            "it": "Ripristina acquisti",
            "pl": "Przywróć zakupy",
            "nl": "Aankopen herstellen",
            "ms": "Pulihkan pembelian",
            "fil": "I-restore ang mga pagbili",
            "ur": "خریداریاں بحال کریں",
            "bn": "কেনাকাটা পুনরুদ্ধার করুন",
            "fa": "بازیابی خریدها",
            "uk": "Відновити покупки",
            "ro": "Restaurează achizițiile",
            "cs": "Obnovit nákupy",
            "sv": "Återställ köp",
            "el": "Επαναφορά αγορών",
            "he": "שחזור רכישות",
            "hu": "Vásárlások visszaállítása",
            "da": "Gendan køb",
            "fi": "Palauta ostokset",
            "nb": "Gjenopprett kjøp",
            "sk": "Obnoviť nákupy",
            "hr": "Vrati kupnje",
            "bg": "Възстанови покупки",
            "sw": "Rejesha ununuzi",
            "ca": "Restaura les compres",
        },
        "paywall.close": {
            "en": "Close",
            "tr": "Kapat",
            "es": "Cerrar",
            "es-419": "Cerrar",
            "pt-BR": "Fechar",
            "pt-PT": "Fechar",
            "hi": "बंद करें",
            "id": "Tutup",
            "ar": "إغلاق",
            "ru": "Закрыть",
            "de": "Schließen",
            "fr": "Fermer",
            "ja": "閉じる",
            "ko": "닫기",
            "zh-Hans": "关闭",
            "zh-Hant": "關閉",
            "vi": "Đóng",
            "th": "ปิด",
            "it": "Chiudi",
            "pl": "Zamknij",
            "nl": "Sluiten",
            "ms": "Tutup",
            "fil": "Isara",
            "ur": "بند کریں",
            "bn": "বন্ধ করুন",
            "fa": "بستن",
            "uk": "Закрити",
            "ro": "Închide",
            "cs": "Zavřít",
            "sv": "Stäng",
            "el": "Κλείσιμο",
            "he": "סגור",
            "hu": "Bezárás",
            "da": "Luk",
            "fi": "Sulje",
            "nb": "Lukk",
            "sk": "Zavrieť",
            "hr": "Zatvori",
            "bg": "Затвори",
            "sw": "Funga",
            "ca": "Tanca",
        },
    }
