#!/usr/bin/env python3
"""Generate Localizable.xcstrings for Google Play top-volume languages."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "CarDoctor" / "Resources" / "Localizable.xcstrings"

# Google Play highest-volume + high-value locales (BCP-47 / Apple String Catalog codes).
# Sourced from Play download leaders (IN, BR, US, ID, MX, PH, TR, PK, EG, DE, …)
# plus common Play Console store languages.
LANGS = [
    "en",
    "tr",
    "es",
    "es-419",
    "pt-BR",
    "pt-PT",
    "hi",
    "id",
    "ar",
    "ru",
    "de",
    "fr",
    "ja",
    "ko",
    "zh-Hans",
    "zh-Hant",
    "vi",
    "th",
    "it",
    "pl",
    "nl",
    "ms",
    "fil",
    "ur",
    "bn",
    "fa",
    "uk",
    "ro",
    "cs",
    "sv",
    "el",
    "he",
    "hu",
    "da",
    "fi",
    "nb",
    "sk",
    "hr",
    "bg",
    "sw",
    "ca",
]

# key -> { lang -> value }
T: dict[str, dict[str, str]] = {
    "tab.diagnose": {
        "en": "Diagnose",
        "tr": "Teşhis",
        "es": "Diagnosticar",
        "es-419": "Diagnosticar",
        "pt-BR": "Diagnosticar",
        "pt-PT": "Diagnosticar",
        "hi": "निदान",
        "id": "Diagnosis",
        "ar": "تشخيص",
        "ru": "Диагностика",
        "de": "Diagnose",
        "fr": "Diagnostiquer",
        "ja": "診断",
        "ko": "진단",
        "zh-Hans": "诊断",
        "zh-Hant": "診斷",
        "vi": "Chẩn đoán",
        "th": "วินิจฉัย",
        "it": "Diagnosi",
        "pl": "Diagnostyka",
        "nl": "Diagnose",
        "ms": "Diagnosa",
        "fil": "Diagnose",
        "ur": "تشخیص",
        "bn": "নির্ণয়",
        "fa": "تشخیص",
        "uk": "Діагностика",
        "ro": "Diagnostic",
        "cs": "Diagnostika",
        "sv": "Diagnos",
        "el": "Διάγνωση",
        "he": "אבחון",
        "hu": "Diagnózis",
        "da": "Diagnose",
        "fi": "Diagnoosi",
        "nb": "Diagnose",
        "sk": "Diagnostika",
        "hr": "Dijagnostika",
        "bg": "Диагностика",
        "sw": "Tambua",
        "ca": "Diagnosticar",
    },
    "tab.community": {
        "en": "Community",
        "tr": "Topluluk",
        "es": "Comunidad",
        "es-419": "Comunidad",
        "pt-BR": "Comunidade",
        "pt-PT": "Comunidade",
        "hi": "समुदाय",
        "id": "Komunitas",
        "ar": "المجتمع",
        "ru": "Сообщество",
        "de": "Community",
        "fr": "Communauté",
        "ja": "コミュニティ",
        "ko": "커뮤니티",
        "zh-Hans": "社区",
        "zh-Hant": "社群",
        "vi": "Cộng đồng",
        "th": "ชุมชน",
        "it": "Community",
        "pl": "Społeczność",
        "nl": "Community",
        "ms": "Komuniti",
        "fil": "Komunidad",
        "ur": "کمیونٹی",
        "bn": "কমিউনিটি",
        "fa": "انجمن",
        "uk": "Спільнота",
        "ro": "Comunitate",
        "cs": "Komunita",
        "sv": "Community",
        "el": "Κοινότητα",
        "he": "קהילה",
        "hu": "Közösség",
        "da": "Fællesskab",
        "fi": "Yhteisö",
        "nb": "Fellesskap",
        "sk": "Komunita",
        "hr": "Zajednica",
        "bg": "Общност",
        "sw": "Jumuiya",
        "ca": "Comunitat",
    },
    "tab.upload": {
        "en": "Upload",
        "tr": "Yükle",
        "es": "Subir",
        "es-419": "Subir",
        "pt-BR": "Enviar",
        "pt-PT": "Carregar",
        "hi": "अपलोड",
        "id": "Unggah",
        "ar": "رفع",
        "ru": "Загрузить",
        "de": "Hochladen",
        "fr": "Importer",
        "ja": "アップロード",
        "ko": "업로드",
        "zh-Hans": "上传",
        "zh-Hant": "上傳",
        "vi": "Tải lên",
        "th": "อัปโหลด",
        "it": "Carica",
        "pl": "Prześlij",
        "nl": "Uploaden",
        "ms": "Muat naik",
        "fil": "I-upload",
        "ur": "اپ لوڈ",
        "bn": "আপলোড",
        "fa": "آپلود",
        "uk": "Завантажити",
        "ro": "Încarcă",
        "cs": "Nahrát",
        "sv": "Ladda upp",
        "el": "Μεταφόρτωση",
        "he": "העלאה",
        "hu": "Feltöltés",
        "da": "Upload",
        "fi": "Lataa",
        "nb": "Last opp",
        "sk": "Nahrať",
        "hr": "Učitaj",
        "bg": "Качване",
        "sw": "Pakia",
        "ca": "Puja",
    },
    "tab.profile": {
        "en": "Profile",
        "tr": "Profil",
        "es": "Perfil",
        "es-419": "Perfil",
        "pt-BR": "Perfil",
        "pt-PT": "Perfil",
        "hi": "प्रोफ़ाइल",
        "id": "Profil",
        "ar": "الملف الشخصي",
        "ru": "Профиль",
        "de": "Profil",
        "fr": "Profil",
        "ja": "プロフィール",
        "ko": "프로필",
        "zh-Hans": "个人资料",
        "zh-Hant": "個人檔案",
        "vi": "Hồ sơ",
        "th": "โปรไฟล์",
        "it": "Profilo",
        "pl": "Profil",
        "nl": "Profiel",
        "ms": "Profil",
        "fil": "Profile",
        "ur": "پروفائل",
        "bn": "প্রোফাইল",
        "fa": "پروفایل",
        "uk": "Профіль",
        "ro": "Profil",
        "cs": "Profil",
        "sv": "Profil",
        "el": "Προφίλ",
        "he": "פרופיל",
        "hu": "Profil",
        "da": "Profil",
        "fi": "Profiili",
        "nb": "Profil",
        "sk": "Profil",
        "hr": "Profil",
        "bg": "Профил",
        "sw": "Wasifu",
        "ca": "Perfil",
    },
    "auth.tagline": {
        "en": "VIN + fault code → part, repair steps, and 3D guidance from the community.",
        "tr": "Şasi + arıza kodu → parça, tamir adımları ve topluluktan 3D rehberlik.",
        "es": "VIN + código de fallo → pieza, pasos de reparación y guía 3D de la comunidad.",
        "es-419": "VIN + código de falla → pieza, pasos de reparación y guía 3D de la comunidad.",
        "pt-BR": "VIN + código de falha → peça, passos de reparo e orientação 3D da comunidade.",
        "pt-PT": "VIN + código de avaria → peça, passos de reparação e orientação 3D da comunidade.",
        "hi": "VIN + दोष कोड → पार्ट, मरम्मत चरण और समुदाय से 3D मार्गदर्शन।",
        "id": "VIN + kode kesalahan → suku cadang, langkah perbaikan, dan panduan 3D dari komunitas.",
        "ar": "رقم الهيكل + رمز العطل ← القطعة وخطوات الإصلاح وإرشاد ثلاثي الأبعاد من المجتمع.",
        "ru": "VIN + код ошибки → деталь, шаги ремонта и 3D‑подсказки от сообщества.",
        "de": "FIN + Fehlercode → Teil, Reparaturschritte und 3D‑Hilfe aus der Community.",
        "fr": "VIN + code défaut → pièce, étapes de réparation et guide 3D de la communauté.",
        "ja": "VIN＋故障コード → 部品、修理手順、コミュニティの3Dガイド。",
        "ko": "VIN + 고장 코드 → 부품, 수리 단계, 커뮤니티의 3D 안내.",
        "zh-Hans": "VIN + 故障码 → 零件、维修步骤以及社区的 3D 指引。",
        "zh-Hant": "VIN + 故障碼 → 零件、維修步驟以及社群的 3D 指引。",
        "vi": "VIN + mã lỗi → phụ tùng, bước sửa chữa và hướng dẫn 3D từ cộng đồng.",
        "th": "VIN + รหัสความผิดปกติ → อะไหล่ ขั้นตอนซ่อม และคำแนะนำ 3D จากชุมชน",
        "it": "VIN + codice guasto → pezzo, passaggi di riparazione e guida 3D dalla community.",
        "pl": "VIN + kod usterki → część, kroki naprawy i wskazówki 3D od społeczności.",
        "nl": "VIN + storingscode → onderdeel, reparatiestappen en 3D-hulp van de community.",
        "ms": "VIN + kod kerosakan → bahagian, langkah pembaikan dan panduan 3D dari komuniti.",
        "fil": "VIN + fault code → parte, hakbang sa pagkumpuni, at 3D gabay mula sa komunidad.",
        "ur": "VIN + خرابی کوڈ → پرزہ، مرمت کے مراحل اور کمیونٹی سے 3D رہنمائی۔",
        "bn": "VIN + ত্রুটি কোড → যন্ত্রাংশ, মেরামত ধাপ এবং কমিউনিটির 3D নির্দেশনা।",
        "fa": "VIN + کد خطا ← قطعه، مراحل تعمیر و راهنمای سه‌بعدی از جامعه.",
        "uk": "VIN + код несправності → деталь, кроки ремонту та 3D‑підказки від спільноти.",
        "ro": "VIN + cod de eroare → piesă, pași de reparație și ghid 3D din comunitate.",
        "cs": "VIN + chybový kód → díl, kroky opravy a 3D návod od komunity.",
        "sv": "VIN + felkod → del, reparationssteg och 3D‑vägledning från communityn.",
        "el": "VIN + κωδικός βλάβης → εξάρτημα, βήματα επισκευής και 3D καθοδήγηση από την κοινότητα.",
        "he": "מספר שלדה + קוד תקלה ← חלק, שלבי תיקון והכוונה תלת־ממדית מהקהילה.",
        "hu": "Alvázszám + hibakód → alkatrész, javítási lépések és 3D útmutató a közösségtől.",
        "da": "VIN + fejlkode → del, reparationstrin og 3D-vejledning fra fællesskabet.",
        "fi": "VIN + vikakoodi → osa, korjausvaiheet ja 3D-opastus yhteisöltä.",
        "nb": "VIN + feilkode → del, reparasjonstrinn og 3D-veiledning fra fellesskapet.",
        "sk": "VIN + chybový kód → diel, kroky opravy a 3D návod od komunity.",
        "hr": "VIN + kod kvara → dio, koraci popravka i 3D vodič zajednice.",
        "bg": "VIN + код на грешка → част, стъпки за ремонт и 3D насоки от общността.",
        "sw": "VIN + msimbo wa hitilafu → sehemu, hatua za ukarabati na mwongozo wa 3D kutoka jumuiya.",
        "ca": "VIN + codi d’avaria → peça, passos de reparació i guia 3D de la comunitat.",
    },
    "auth.demo": {
        "en": "Continue with Demo",
        "tr": "Demo ile devam et",
        "es": "Continuar con Demo",
        "es-419": "Continuar con Demo",
        "pt-BR": "Continuar com Demo",
        "pt-PT": "Continuar com Demo",
        "hi": "डेमो के साथ जारी रखें",
        "id": "Lanjutkan dengan Demo",
        "ar": "المتابعة بالتجربة",
        "ru": "Продолжить в демо",
        "de": "Mit Demo fortfahren",
        "fr": "Continuer en démo",
        "ja": "デモで続行",
        "ko": "데모로 계속",
        "zh-Hans": "使用演示继续",
        "zh-Hant": "使用示範繼續",
        "vi": "Tiếp tục với bản demo",
        "th": "ดำเนินการต่อด้วยเดโม",
        "it": "Continua con Demo",
        "pl": "Kontynuuj w trybie demo",
        "nl": "Doorgaan met demo",
        "ms": "Teruskan dengan Demo",
        "fil": "Magpatuloy sa Demo",
        "ur": "ڈیمو کے ساتھ جاری رکھیں",
        "bn": "ডেমো দিয়ে চালিয়ে যান",
        "fa": "ادامه با نسخه آزمایشی",
        "uk": "Продовжити в демо",
        "ro": "Continuă cu Demo",
        "cs": "Pokračovat v demu",
        "sv": "Fortsätt med demo",
        "el": "Συνέχεια με Demo",
        "he": "המשך עם הדגמה",
        "hu": "Folytatás demóval",
        "da": "Fortsæt med demo",
        "fi": "Jatka demolla",
        "nb": "Fortsett med demo",
        "sk": "Pokračovať v deme",
        "hr": "Nastavi s demom",
        "bg": "Продължи с демо",
        "sw": "Endelea na Demo",
        "ca": "Continua amb la demostració",
    },
}


def _fill_remaining() -> None:
    """Add the rest of UI keys (split for readability)."""
    more: dict[str, dict[str, str]] = {
        "diagnose.headline": {
            "en": "Find the fault",
            "tr": "Arızayı bul",
            "es": "Encuentra el fallo",
            "es-419": "Encuentra la falla",
            "pt-BR": "Encontre a falha",
            "pt-PT": "Encontre a avaria",
            "hi": "दोष खोजें",
            "id": "Temukan kesalahan",
            "ar": "اعثر على العطل",
            "ru": "Найдите неисправность",
            "de": "Fehler finden",
            "fr": "Trouver le défaut",
            "ja": "故障を特定",
            "ko": "고장 찾기",
            "zh-Hans": "查找故障",
            "zh-Hant": "找出故障",
            "vi": "Tìm lỗi",
            "th": "ค้นหาความผิดปกติ",
            "it": "Trova il guasto",
            "pl": "Znajdź usterkę",
            "nl": "Vind de storing",
            "ms": "Cari kerosakan",
            "fil": "Hanapin ang sira",
            "ur": "خرابی تلاش کریں",
            "bn": "ত্রুটি খুঁজুন",
            "fa": "عیب را پیدا کنید",
            "uk": "Знайдіть несправність",
            "ro": "Găsește defectul",
            "cs": "Najděte závadu",
            "sv": "Hitta felet",
            "el": "Βρείτε τη βλάβη",
            "he": "מצא את התקלה",
            "hu": "Hibakeresés",
            "da": "Find fejlen",
            "fi": "Löydä vika",
            "nb": "Finn feilen",
            "sk": "Nájdite poruchu",
            "hr": "Pronađi kvar",
            "bg": "Открийте повредата",
            "sw": "Tafuta hitilafu",
            "ca": "Troba l’avaria",
        },
        "diagnose.subtitle": {
            "en": "Enter a specific VIN and fault code — diagnosis is resolved per vehicle brand.",
            "tr": "Spesifik VIN ve arıza kodunu gir — teşhis araç markasına göre çözülür.",
            "es": "Introduce un VIN y un código de fallo concretos; el diagnóstico se resuelve por marca.",
            "es-419": "Ingresa un VIN y un código de falla específicos; el diagnóstico se resuelve por marca.",
            "pt-BR": "Informe um VIN e um código de falha específicos — o diagnóstico é por marca do veículo.",
            "pt-PT": "Introduza um VIN e um código de avaria específicos — o diagnóstico é por marca.",
            "hi": "विशिष्ट VIN और दोष कोड दर्ज करें — निदान वाहन ब्रांड के अनुसार होता है।",
            "id": "Masukkan VIN dan kode kesalahan spesifik — diagnosis diselesaikan per merek kendaraan.",
            "ar": "أدخل رقم هيكل ورمز عطل محددين — يتم التشخيص حسب ماركة المركبة.",
            "ru": "Введите конкретный VIN и код ошибки — диагностика зависит от марки автомобиля.",
            "de": "Geben Sie eine konkrete FIN und einen Fehlercode ein — die Diagnose erfolgt markenspezifisch.",
            "fr": "Saisissez un VIN et un code défaut précis — le diagnostic est résolu par marque.",
            "ja": "具体的なVINと故障コードを入力 — 診断は車種メーカーごとに解決されます。",
            "ko": "구체적인 VIN과 고장 코드를 입력하세요 — 진단은 차량 브랜드별로 처리됩니다.",
            "zh-Hans": "输入具体的 VIN 和故障码 — 诊断按车辆品牌解析。",
            "zh-Hant": "輸入具體的 VIN 和故障碼 — 診斷依車輛品牌解析。",
            "vi": "Nhập VIN và mã lỗi cụ thể — chẩn đoán được giải quyết theo từng hãng xe.",
            "th": "ใส่ VIN และรหัสความผิดปกติที่เฉพาะเจาะจง — การวินิจฉัยแยกตามยี่ห้อรถ",
            "it": "Inserisci un VIN e un codice guasto specifici — la diagnosi è per marca del veicolo.",
            "pl": "Wpisz konkretny VIN i kod usterki — diagnoza jest rozwiązywana według marki.",
            "nl": "Voer een specifiek VIN en een storingscode in — diagnose per voertuigmerk.",
            "ms": "Masukkan VIN dan kod kerosakan khusus — diagnosis diselesaikan mengikut jenama kenderaan.",
            "fil": "Ilagay ang partikular na VIN at fault code — ang diagnosis ay ayon sa brand ng sasakyan.",
            "ur": "مخصوص VIN اور خرابی کوڈ درج کریں — تشخیص گاڑی کے برانڈ کے مطابق ہوتی ہے۔",
            "bn": "নির্দিষ্ট VIN ও ত্রুটি কোড লিখুন — নির্ণয় যানবাহনের ব্র্যান্ড অনুযায়ী হয়।",
            "fa": "VIN و کد خطای مشخص وارد کنید — تشخیص بر اساس برند خودرو انجام می‌شود.",
            "uk": "Введіть конкретний VIN і код несправності — діагностика залежить від марки авто.",
            "ro": "Introdu un VIN și un cod de eroare specifice — diagnosticul se rezolvă pe marcă.",
            "cs": "Zadejte konkrétní VIN a chybový kód — diagnostika se řeší podle značky vozidla.",
            "sv": "Ange ett specifikt VIN och en felkod — diagnosen löses per fordonsmärke.",
            "el": "Εισαγάγετε συγκεκριμένο VIN και κωδικό βλάβης — η διάγνωση γίνεται ανά μάρκα οχήματος.",
            "he": "הזן מספר שלדה וקוד תקלה ספציפיים — האבחון נפתר לפי מותג הרכב.",
            "hu": "Adjon meg egy konkrét alvázszámot és hibakódot — a diagnózis márkánként történik.",
            "da": "Indtast et specifikt VIN og en fejlkode — diagnosen løses pr. bilmærke.",
            "fi": "Anna tietty VIN ja vikakoodi — diagnoosi ratkaistaan ajoneuvomerkin mukaan.",
            "nb": "Skriv inn et spesifikt VIN og en feilkode — diagnosen løses per bilmerke.",
            "sk": "Zadajte konkrétne VIN a chybový kód — diagnostika sa rieši podľa značky vozidla.",
            "hr": "Unesite konkretan VIN i kod kvara — dijagnostika se rješava po marki vozila.",
            "bg": "Въведете конкретен VIN и код на грешка — диагностиката е по марка на автомобила.",
            "sw": "Weka VIN na msimbo wa hitilafu mahususi — utambuzi unatatuliwa kwa chapa ya gari.",
            "ca": "Introdueix un VIN i un codi d’avaria concrets — el diagnòstic es resol per marca.",
        },
        "diagnose.vin": {
            "en": "VIN / Chassis",
            "tr": "VIN / Şasi",
            "es": "VIN / Chasis",
            "es-419": "VIN / Chasis",
            "pt-BR": "VIN / Chassi",
            "pt-PT": "VIN / Chassis",
            "hi": "VIN / चेसिस",
            "id": "VIN / Sasis",
            "ar": "رقم الهيكل / الشاسيه",
            "ru": "VIN / Шасси",
            "de": "FIN / Fahrgestell",
            "fr": "VIN / Châssis",
            "ja": "VIN / 車台番号",
            "ko": "VIN / 차대번호",
            "zh-Hans": "VIN / 车架号",
            "zh-Hant": "VIN / 車架號碼",
            "vi": "VIN / Khung xe",
            "th": "VIN / หมายเลขตัวถัง",
            "it": "VIN / Telaio",
            "pl": "VIN / Podwozie",
            "nl": "VIN / Chassis",
            "ms": "VIN / Casis",
            "fil": "VIN / Chassis",
            "ur": "VIN / شاسی",
            "bn": "VIN / চেসিস",
            "fa": "VIN / شاسی",
            "uk": "VIN / Шасі",
            "ro": "VIN / Șasiu",
            "cs": "VIN / Podvozek",
            "sv": "VIN / Chassi",
            "el": "VIN / Πλαίσιο",
            "he": "מספר שלדה",
            "hu": "Alvázszám / VIN",
            "da": "VIN / Chassis",
            "fi": "VIN / Runko",
            "nb": "VIN / Chassis",
            "sk": "VIN / Podvozok",
            "hr": "VIN / Šasija",
            "bg": "VIN / Шаси",
            "sw": "VIN / Chasi",
            "ca": "VIN / Xassís",
        },
        "diagnose.dtc": {
            "en": "Fault code (DTC)",
            "tr": "Arıza kodu (DTC)",
            "es": "Código de fallo (DTC)",
            "es-419": "Código de falla (DTC)",
            "pt-BR": "Código de falha (DTC)",
            "pt-PT": "Código de avaria (DTC)",
            "hi": "दोष कोड (DTC)",
            "id": "Kode kesalahan (DTC)",
            "ar": "رمز العطل (DTC)",
            "ru": "Код ошибки (DTC)",
            "de": "Fehlercode (DTC)",
            "fr": "Code défaut (DTC)",
            "ja": "故障コード（DTC）",
            "ko": "고장 코드(DTC)",
            "zh-Hans": "故障码（DTC）",
            "zh-Hant": "故障碼（DTC）",
            "vi": "Mã lỗi (DTC)",
            "th": "รหัสความผิดปกติ (DTC)",
            "it": "Codice guasto (DTC)",
            "pl": "Kod usterki (DTC)",
            "nl": "Storingscode (DTC)",
            "ms": "Kod kerosakan (DTC)",
            "fil": "Fault code (DTC)",
            "ur": "خرابی کوڈ (DTC)",
            "bn": "ত্রুটি কোড (DTC)",
            "fa": "کد خطا (DTC)",
            "uk": "Код несправності (DTC)",
            "ro": "Cod de eroare (DTC)",
            "cs": "Chybový kód (DTC)",
            "sv": "Felkod (DTC)",
            "el": "Κωδικός βλάβης (DTC)",
            "he": "קוד תקלה (DTC)",
            "hu": "Hibakód (DTC)",
            "da": "Fejlkode (DTC)",
            "fi": "Vikakoodi (DTC)",
            "nb": "Feilkode (DTC)",
            "sk": "Chybový kód (DTC)",
            "hr": "Kod kvara (DTC)",
            "bg": "Код на грешка (DTC)",
            "sw": "Msimbo wa hitilafu (DTC)",
            "ca": "Codi d’avaria (DTC)",
        },
        "diagnose.submit": {
            "en": "Diagnose",
            "tr": "Teşhis et",
            "es": "Diagnosticar",
            "es-419": "Diagnosticar",
            "pt-BR": "Diagnosticar",
            "pt-PT": "Diagnosticar",
            "hi": "निदान करें",
            "id": "Diagnosa",
            "ar": "تشخيص",
            "ru": "Диагностировать",
            "de": "Diagnostizieren",
            "fr": "Diagnostiquer",
            "ja": "診断する",
            "ko": "진단하기",
            "zh-Hans": "开始诊断",
            "zh-Hant": "開始診斷",
            "vi": "Chẩn đoán",
            "th": "วินิจฉัย",
            "it": "Diagnostica",
            "pl": "Diagnostikuj",
            "nl": "Diagnoseer",
            "ms": "Diagnosa",
            "fil": "I-diagnose",
            "ur": "تشخیص کریں",
            "bn": "নির্ণয় করুন",
            "fa": "تشخیص بده",
            "uk": "Діагностувати",
            "ro": "Diagnozează",
            "cs": "Diagnostikovat",
            "sv": "Diagnostisera",
            "el": "Διάγνωση",
            "he": "אבחן",
            "hu": "Diagnosztizálás",
            "da": "Diagnosticer",
            "fi": "Diagnosoi",
            "nb": "Diagnostiser",
            "sk": "Diagnostikovať",
            "hr": "Dijagnosticiraj",
            "bg": "Диагностицирай",
            "sw": "Tambua",
            "ca": "Diagnosticar",
        },
        "diagnose.samples": {
            "en": "Try a common code",
            "tr": "Yaygın bir kod dene",
            "es": "Prueba un código habitual",
            "es-419": "Prueba un código común",
            "pt-BR": "Experimente um código comum",
            "pt-PT": "Experimente um código comum",
            "hi": "एक सामान्य कोड आज़माएँ",
            "id": "Coba kode umum",
            "ar": "جرّب رمزًا شائعًا",
            "ru": "Попробуйте распространённый код",
            "de": "Häufigen Code ausprobieren",
            "fr": "Essayer un code courant",
            "ja": "よくあるコードを試す",
            "ko": "흔한 코드 사용해 보기",
            "zh-Hans": "试试常见代码",
            "zh-Hant": "試試常見代碼",
            "vi": "Thử mã phổ biến",
            "th": "ลองรหัสที่ใช้บ่อย",
            "it": "Prova un codice comune",
            "pl": "Wypróbuj popularny kod",
            "nl": "Probeer een veelvoorkomende code",
            "ms": "Cuba kod biasa",
            "fil": "Subukan ang karaniwang code",
            "ur": "عام کوڈ آزمائیں",
            "bn": "একটি সাধারণ কোড চেষ্টা করুন",
            "fa": "یک کد رایج را امتحان کنید",
            "uk": "Спробуйте поширений код",
            "ro": "Încearcă un cod comun",
            "cs": "Vyzkoušejte běžný kód",
            "sv": "Prova en vanlig kod",
            "el": "Δοκιμάστε έναν συνηθισμένο κωδικό",
            "he": "נסה קוד נפוץ",
            "hu": "Próbáljon egy gyakori kódot",
            "da": "Prøv en almindelig kode",
            "fi": "Kokeile yleistä koodia",
            "nb": "Prøv en vanlig kode",
            "sk": "Vyskúšajte bežný kód",
            "hr": "Isprobaj uobičajeni kod",
            "bg": "Опитайте често срещан код",
            "sw": "Jaribu msimbo wa kawaida",
            "ca": "Prova un codi habitual",
        },
        "diagnose.samples.brand": {
            "en": "Codes for this brand",
            "tr": "Bu markaya özel kodlar",
            "es": "Códigos de esta marca",
            "es-419": "Códigos de esta marca",
            "pt-BR": "Códigos desta marca",
            "pt-PT": "Códigos desta marca",
            "hi": "इस ब्रांड के कोड",
            "id": "Kode untuk merek ini",
            "ar": "رموز هذه الماركة",
            "ru": "Коды для этой марки",
            "de": "Codes für diese Marke",
            "fr": "Codes pour cette marque",
            "ja": "このメーカーのコード",
            "ko": "이 브랜드의 코드",
            "zh-Hans": "该品牌的代码",
            "zh-Hant": "此品牌的代碼",
            "vi": "Mã cho hãng này",
            "th": "รหัสสำหรับยี่ห้อนี้",
            "it": "Codici per questa marca",
            "pl": "Kody dla tej marki",
            "nl": "Codes voor dit merk",
            "ms": "Kod untuk jenama ini",
            "fil": "Mga code para sa brand na ito",
            "ur": "اس برانڈ کے کوڈز",
            "bn": "এই ব্র্যান্ডের কোড",
            "fa": "کدهای این برند",
            "uk": "Коди для цієї марки",
            "ro": "Coduri pentru această marcă",
            "cs": "Kódy pro tuto značku",
            "sv": "Koder för detta märke",
            "el": "Κωδικοί για αυτή τη μάρκα",
            "he": "קודים למותג זה",
            "hu": "Kódok ehhez a márkához",
            "da": "Koder til dette mærke",
            "fi": "Tämän merkin koodit",
            "nb": "Koder for dette merket",
            "sk": "Kódy pre túto značku",
            "hr": "Kodovi za ovu marku",
            "bg": "Кодове за тази марка",
            "sw": "Misimbo ya chapa hii",
            "ca": "Codis d’aquesta marca",
        },
        "diagnose.brandSpecific": {
            "en": "Brand-specific diagnosis enabled",
            "tr": "Markaya özel teşhis hazır",
            "es": "Diagnóstico específico de marca activado",
            "es-419": "Diagnóstico específico de marca activado",
            "pt-BR": "Diagnóstico específico da marca ativado",
            "pt-PT": "Diagnóstico específico da marca ativado",
            "hi": "ब्रांड-विशिष्ट निदान सक्षम",
            "id": "Diagnosis khusus merek diaktifkan",
            "ar": "تم تفعيل التشخيص الخاص بالماركة",
            "ru": "Включена диагностика для марки",
            "de": "Markenspezifische Diagnose aktiv",
            "fr": "Diagnostic spécifique à la marque activé",
            "ja": "メーカー別診断が有効",
            "ko": "브랜드별 진단 활성화됨",
            "zh-Hans": "已启用品牌专属诊断",
            "zh-Hant": "已啟用品牌專屬診斷",
            "vi": "Đã bật chẩn đoán theo hãng",
            "th": "เปิดใช้การวินิจฉัยเฉพาะยี่ห้อแล้ว",
            "it": "Diagnosi specifica per marca attiva",
            "pl": "Włączona diagnostyka dla marki",
            "nl": "Merk-specifieke diagnose ingeschakeld",
            "ms": "Diagnosis khusus jenama diaktifkan",
            "fil": "Naka-enable ang diagnosis para sa brand",
            "ur": "برانڈ مخصوص تشخیص فعال",
            "bn": "ব্র্যান্ড-নির্দিষ্ট নির্ণয় সক্রিয়",
            "fa": "تشخیص اختصاصی برند فعال شد",
            "uk": "Увімкнено діагностику для марки",
            "ro": "Diagnostic specific mărcii activat",
            "cs": "Diagnostika pro značku je aktivní",
            "sv": "Märkesspecifik diagnos aktiverad",
            "el": "Ενεργή διάγνωση ανά μάρκα",
            "he": "אבחון ספציפי למותג פעיל",
            "hu": "Márkaspecifikus diagnózis bekapcsolva",
            "da": "Mærkespecifik diagnose aktiveret",
            "fi": "Merkkikohtainen diagnoosi käytössä",
            "nb": "Merke-spesifikk diagnose aktivert",
            "sk": "Diagnostika pre značku je aktívna",
            "hr": "Omogućena dijagnostika za marku",
            "bg": "Активирана е диагностика по марка",
            "sw": "Utambuzi wa chapa umewezeshwa",
            "ca": "Diagnòstic específic de marca activat",
        },
    }
    T.update(more)


def _fill_errors_and_result() -> None:
    T.update(
        {
            "legal.disclaimer": {
                "en": "For informational purposes only. Not a substitute for professional service advice. Follow safety procedures.",
                "tr": "Yalnızca bilgilendirme amaçlıdır. Profesyonel servis tavsiyesinin yerini tutmaz. Güvenlik prosedürlerine uyun.",
                "es": "Solo con fines informativos. No sustituye el consejo de un taller profesional. Siga las medidas de seguridad.",
                "es-419": "Solo con fines informativos. No sustituye el consejo de un taller profesional. Sigue las medidas de seguridad.",
                "pt-BR": "Apenas para informação. Não substitui orientação profissional. Siga os procedimentos de segurança.",
                "pt-PT": "Apenas para fins informativos. Não substitui aconselhamento profissional. Siga os procedimentos de segurança.",
                "hi": "केवल सूचना हेतु। पेशेवर सेवा सलाह का विकल्प नहीं। सुरक्षा प्रक्रियाओं का पालन करें।",
                "id": "Hanya untuk informasi. Bukan pengganti saran bengkel profesional. Ikuti prosedur keselamatan.",
                "ar": "لأغراض معلوماتية فقط. لا يغني عن استشارة خدمة محترفة. اتبع إجراءات السلامة.",
                "ru": "Только для информации. Не заменяет совет профессионального сервиса. Соблюдайте технику безопасности.",
                "de": "Nur zu Informationszwecken. Kein Ersatz für professionellen Werkstattservice. Sicherheitsregeln beachten.",
                "fr": "À titre informatif uniquement. Ne remplace pas un avis professionnel. Respectez les consignes de sécurité.",
                "ja": "情報提供のみです。専門整備の代替ではありません。安全手順に従ってください。",
                "ko": "정보 제공 목적입니다. 전문 정비 조언을 대체하지 않습니다. 안전 절차를 따르세요.",
                "zh-Hans": "仅供参考。不能替代专业维修建议。请遵守安全规程。",
                "zh-Hant": "僅供參考。不能取代專業維修建議。請遵守安全程序。",
                "vi": "Chỉ mang tính thông tin. Không thay thế tư vấn sửa chữa chuyên nghiệp. Tuân thủ quy trình an toàn.",
                "th": "เพื่อข้อมูลเท่านั้น ไม่ใช่คำแนะนำจากช่างมืออาชีพ โปรดปฏิบัติตามขั้นตอนความปลอดภัย",
                "it": "Solo a scopo informativo. Non sostituisce il consiglio di un’officina. Seguire le procedure di sicurezza.",
                "pl": "Wyłącznie w celach informacyjnych. Nie zastępuje porady warsztatu. Przestrzegaj procedur bezpieczeństwa.",
                "nl": "Alleen ter informatie. Geen vervanging van professioneel advies. Volg veiligheidsprocedures.",
                "ms": "Untuk maklumat sahaja. Bukan pengganti nasihat servis profesional. Patuhi prosedur keselamatan.",
                "fil": "Para sa impormasyon lamang. Hindi kapalit ng propesyonal na payo. Sundin ang mga safety procedure.",
                "ur": "صرف معلومات کے لیے۔ پیشہ ورانہ سروس مشورے کا متبادل نہیں۔ حفاظتی طریقہ کار پر عمل کریں۔",
                "bn": "শুধু তথ্যের জন্য। পেশাদার সার্ভিস পরামর্শের বিকল্প নয়। নিরাপত্তা পদ্ধতি মেনে চলুন।",
                "fa": "فقط برای اطلاع‌رسانی. جایگزین مشاوره تخصصی نیست. رویه‌های ایمنی را رعایت کنید.",
                "uk": "Лише для інформації. Не замінює пораду професійного сервісу. Дотримуйтесь правил безпеки.",
                "ro": "Doar în scop informativ. Nu înlocuiește sfatul unui service profesionist. Respectați procedurile de siguranță.",
                "cs": "Pouze pro informaci. Nenahrazuje odborný servis. Dodržujte bezpečnostní postupy.",
                "sv": "Endast i informationssyfte. Ersätter inte professionell verkstadsrådgivning. Följ säkerhetsrutiner.",
                "el": "Μόνο για ενημέρωση. Δεν υποκαθιστά επαγγελματική συμβουλή. Ακολουθήστε τις διαδικασίες ασφαλείας.",
                "he": "למידע בלבד. אינו מחליף ייעוץ מקצועי. יש לפעול לפי נהלי בטיחות.",
                "hu": "Csak tájékoztató jellegű. Nem helyettesíti a szakszerviz tanácsát. Tartsa be a biztonsági előírásokat.",
                "da": "Kun til information. Erstatter ikke professionel værkstedsrådgivning. Følg sikkerhedsprocedurer.",
                "fi": "Vain tiedoksi. Ei korvaa ammattilaisen neuvoa. Noudata turvallisuusohjeita.",
                "nb": "Kun til informasjon. Erstatter ikke profesjonell verkstedsrådgivning. Følg sikkerhetsprosedyrer.",
                "sk": "Len na informáciu. Nenahrádza odborný servis. Dodržiavajte bezpečnostné postupy.",
                "hr": "Samo u informativne svrhe. Ne zamjenjuje savjet stručnog servisa. Slijedite sigurnosne postupke.",
                "bg": "Само за информация. Не замества професионален съвет. Спазвайте мерките за безопасност.",
                "sw": "Kwa taarifa tu. Sio mbadala wa ushauri wa kitaalamu. Fuata taratibu za usalama.",
                "ca": "Només amb finalitats informatives. No substitueix el consell professional. Seguiu els procediments de seguretat.",
            },
            "error.vin.invalid": {
                "en": "VIN must be 17 characters (no I, O, Q).",
                "tr": "VIN 17 karakter olmalı (I, O, Q yok).",
                "es": "El VIN debe tener 17 caracteres (sin I, O, Q).",
                "es-419": "El VIN debe tener 17 caracteres (sin I, O, Q).",
                "pt-BR": "O VIN deve ter 17 caracteres (sem I, O, Q).",
                "pt-PT": "O VIN deve ter 17 caracteres (sem I, O, Q).",
                "hi": "VIN 17 अक्षर का होना चाहिए (I, O, Q नहीं)।",
                "id": "VIN harus 17 karakter (tanpa I, O, Q).",
                "ar": "يجب أن يتكون رقم الهيكل من 17 حرفًا (بدون I أو O أو Q).",
                "ru": "VIN должен содержать 17 символов (без I, O, Q).",
                "de": "FIN muss 17 Zeichen haben (ohne I, O, Q).",
                "fr": "Le VIN doit comporter 17 caractères (sans I, O, Q).",
                "ja": "VINは17文字である必要があります（I・O・Qは不可）。",
                "ko": "VIN은 17자여야 합니다(I, O, Q 제외).",
                "zh-Hans": "VIN 必须为 17 位字符（不含 I、O、Q）。",
                "zh-Hant": "VIN 必須為 17 個字元（不含 I、O、Q）。",
                "vi": "VIN phải có 17 ký tự (không gồm I, O, Q).",
                "th": "VIN ต้องมี 17 ตัวอักษร (ห้ามใช้ I, O, Q)",
                "it": "Il VIN deve avere 17 caratteri (senza I, O, Q).",
                "pl": "VIN musi mieć 17 znaków (bez I, O, Q).",
                "nl": "VIN moet 17 tekens zijn (geen I, O, Q).",
                "ms": "VIN mesti 17 aksara (tiada I, O, Q).",
                "fil": "Ang VIN ay dapat 17 character (walang I, O, Q).",
                "ur": "VIN 17 حروف کا ہونا چاہیے (I، O، Q نہیں)۔",
                "bn": "VIN অবশ্যই ১৭ অক্ষরের হতে হবে (I, O, Q নয়)।",
                "fa": "VIN باید ۱۷ کاراکتر باشد (بدون I، O، Q).",
                "uk": "VIN має містити 17 символів (без I, O, Q).",
                "ro": "VIN-ul trebuie să aibă 17 caractere (fără I, O, Q).",
                "cs": "VIN musí mít 17 znaků (bez I, O, Q).",
                "sv": "VIN måste vara 17 tecken (utan I, O, Q).",
                "el": "Το VIN πρέπει να έχει 17 χαρακτήρες (χωρίς I, O, Q).",
                "he": "מספר השלדה חייב להיות בן 17 תווים (ללא I, O, Q).",
                "hu": "A VIN 17 karakter legyen (I, O, Q nélkül).",
                "da": "VIN skal være 17 tegn (uden I, O, Q).",
                "fi": "VIN:n on oltava 17 merkkiä (ei I, O, Q).",
                "nb": "VIN må være 17 tegn (uten I, O, Q).",
                "sk": "VIN musí mať 17 znakov (bez I, O, Q).",
                "hr": "VIN mora imati 17 znakova (bez I, O, Q).",
                "bg": "VIN трябва да е 17 символа (без I, O, Q).",
                "sw": "VIN lazima iwe herufi 17 (bila I, O, Q).",
                "ca": "El VIN ha de tenir 17 caràcters (sense I, O, Q).",
            },
            "error.vin.network": {
                "en": "Could not reach VIN service.",
                "tr": "VIN servisine ulaşılamadı.",
                "es": "No se pudo contactar el servicio de VIN.",
                "es-419": "No se pudo contactar el servicio de VIN.",
                "pt-BR": "Não foi possível acessar o serviço de VIN.",
                "pt-PT": "Não foi possível contactar o serviço de VIN.",
                "hi": "VIN सेवा तक पहुँच नहीं सके।",
                "id": "Tidak dapat menghubungi layanan VIN.",
                "ar": "تعذر الوصول إلى خدمة رقم الهيكل.",
                "ru": "Не удалось связаться со службой VIN.",
                "de": "FIN-Dienst nicht erreichbar.",
                "fr": "Impossible d’atteindre le service VIN.",
                "ja": "VINサービスに接続できませんでした。",
                "ko": "VIN 서비스에 연결할 수 없습니다.",
                "zh-Hans": "无法连接 VIN 服务。",
                "zh-Hant": "無法連線 VIN 服務。",
                "vi": "Không thể kết nối dịch vụ VIN.",
                "th": "ติดต่อบริการ VIN ไม่ได้",
                "it": "Impossibile raggiungere il servizio VIN.",
                "pl": "Nie można połączyć się z usługą VIN.",
                "nl": "VIN-service niet bereikbaar.",
                "ms": "Tidak dapat menghubungi perkhidmatan VIN.",
                "fil": "Hindi maabot ang serbisyo ng VIN.",
                "ur": "VIN سروس تک رسائی نہیں ہو سکی۔",
                "bn": "VIN সেবায় পৌঁছানো যায়নি।",
                "fa": "دسترسی به سرویس VIN ممکن نشد.",
                "uk": "Не вдалося з’єднатися зі службою VIN.",
                "ro": "Nu s-a putut contacta serviciul VIN.",
                "cs": "Nelze se připojit ke službě VIN.",
                "sv": "Kunde inte nå VIN-tjänsten.",
                "el": "Αδυναμία σύνδεσης με την υπηρεσία VIN.",
                "he": "לא ניתן להגיע לשירות מספר השלדה.",
                "hu": "A VIN szolgáltatás nem érhető el.",
                "da": "Kunne ikke nå VIN-tjenesten.",
                "fi": "VIN-palveluun ei saatu yhteyttä.",
                "nb": "Kunne ikke nå VIN-tjenesten.",
                "sk": "Nepodarilo sa kontaktovať službu VIN.",
                "hr": "Nije moguće dohvatiti VIN uslugu.",
                "bg": "Няма връзка с услугата за VIN.",
                "sw": "Imeshindwa kufikia huduma ya VIN.",
                "ca": "No s’ha pogut contactar amb el servei de VIN.",
            },
            "error.vin.notFound": {
                "en": "Vehicle not found for this VIN.",
                "tr": "Bu VIN için araç bulunamadı.",
                "es": "No se encontró un vehículo para este VIN.",
                "es-419": "No se encontró un vehículo para este VIN.",
                "pt-BR": "Veículo não encontrado para este VIN.",
                "pt-PT": "Veículo não encontrado para este VIN.",
                "hi": "इस VIN के लिए वाहन नहीं मिला।",
                "id": "Kendaraan tidak ditemukan untuk VIN ini.",
                "ar": "لم يتم العثور على مركبة لهذا الرقم.",
                "ru": "Автомобиль по этому VIN не найден.",
                "de": "Kein Fahrzeug für diese FIN gefunden.",
                "fr": "Aucun véhicule trouvé pour ce VIN.",
                "ja": "このVINの車両が見つかりません。",
                "ko": "이 VIN에 해당하는 차량을 찾을 수 없습니다.",
                "zh-Hans": "未找到该 VIN 对应的车辆。",
                "zh-Hant": "找不到此 VIN 對應的車輛。",
                "vi": "Không tìm thấy xe cho VIN này.",
                "th": "ไม่พบยานพาหนะสำหรับ VIN นี้",
                "it": "Nessun veicolo trovato per questo VIN.",
                "pl": "Nie znaleziono pojazdu dla tego VIN.",
                "nl": "Geen voertuig gevonden voor dit VIN.",
                "ms": "Kenderaan tidak dijumpai untuk VIN ini.",
                "fil": "Walang nahanap na sasakyan para sa VIN na ito.",
                "ur": "اس VIN کے لیے گاڑی نہیں ملی۔",
                "bn": "এই VIN-এর জন্য যানবাহন পাওয়া যায়নি।",
                "fa": "خودرویی برای این VIN یافت نشد.",
                "uk": "Автомобіль за цим VIN не знайдено.",
                "ro": "Nu s-a găsit vehicul pentru acest VIN.",
                "cs": "Pro toto VIN nebylo vozidlo nalezeno.",
                "sv": "Inget fordon hittades för detta VIN.",
                "el": "Δεν βρέθηκε όχημα για αυτό το VIN.",
                "he": "לא נמצא רכב עבור מספר שלדה זה.",
                "hu": "Ehhez a VIN-hez nem található jármű.",
                "da": "Intet køretøj fundet for dette VIN.",
                "fi": "Tälle VIN-koodille ei löytynyt ajoneuvoa.",
                "nb": "Ingen bil funnet for dette VIN.",
                "sk": "Pre toto VIN sa nenašlo vozidlo.",
                "hr": "Vozilo za ovaj VIN nije pronađeno.",
                "bg": "Не е намерено превозно средство за този VIN.",
                "sw": "Gari halipatikani kwa VIN hii.",
                "ca": "No s’ha trobat cap vehicle per a aquest VIN.",
            },
            "error.dtc.invalid": {
                "en": "Enter a valid code like P0300.",
                "tr": "P0300 gibi geçerli bir kod girin.",
                "es": "Introduce un código válido como P0300.",
                "es-419": "Ingresa un código válido como P0300.",
                "pt-BR": "Informe um código válido como P0300.",
                "pt-PT": "Introduza um código válido como P0300.",
                "hi": "P0300 जैसा मान्य कोड दर्ज करें।",
                "id": "Masukkan kode valid seperti P0300.",
                "ar": "أدخل رمزًا صالحًا مثل P0300.",
                "ru": "Введите корректный код, например P0300.",
                "de": "Geben Sie einen gültigen Code wie P0300 ein.",
                "fr": "Saisissez un code valide comme P0300.",
                "ja": "P0300のような有効なコードを入力してください。",
                "ko": "P0300처럼 유효한 코드를 입력하세요.",
                "zh-Hans": "请输入有效代码，例如 P0300。",
                "zh-Hant": "請輸入有效代碼，例如 P0300。",
                "vi": "Nhập mã hợp lệ như P0300.",
                "th": "ใส่รหัสที่ถูกต้อง เช่น P0300",
                "it": "Inserisci un codice valido come P0300.",
                "pl": "Wpisz prawidłowy kod, np. P0300.",
                "nl": "Voer een geldige code in, zoals P0300.",
                "ms": "Masukkan kod sah seperti P0300.",
                "fil": "Maglagay ng wastong code gaya ng P0300.",
                "ur": "P0300 جیسا درست کوڈ درج کریں۔",
                "bn": "P0300-এর মতো বৈধ কোড লিখুন।",
                "fa": "کد معتبری مانند P0300 وارد کنید.",
                "uk": "Введіть коректний код, наприклад P0300.",
                "ro": "Introdu un cod valid precum P0300.",
                "cs": "Zadejte platný kód, např. P0300.",
                "sv": "Ange en giltig kod som P0300.",
                "el": "Εισαγάγετε έγκυρο κωδικό όπως P0300.",
                "he": "הזן קוד תקין כמו P0300.",
                "hu": "Adjon meg érvényes kódot, pl. P0300.",
                "da": "Indtast en gyldig kode som P0300.",
                "fi": "Anna kelvollinen koodi, esim. P0300.",
                "nb": "Skriv inn en gyldig kode som P0300.",
                "sk": "Zadajte platný kód, napr. P0300.",
                "hr": "Unesite valjani kod poput P0300.",
                "bg": "Въведете валиден код като P0300.",
                "sw": "Weka msimbo halali kama P0300.",
                "ca": "Introdueix un codi vàlid com P0300.",
            },
            "error.dtc.notFound": {
                "en": "This fault code is not in the catalog yet.",
                "tr": "Bu arıza kodu henüz katalogda yok.",
                "es": "Este código de fallo aún no está en el catálogo.",
                "es-419": "Este código de falla aún no está en el catálogo.",
                "pt-BR": "Este código de falha ainda não está no catálogo.",
                "pt-PT": "Este código de avaria ainda não está no catálogo.",
                "hi": "यह दोष कोड अभी कैटलॉग में नहीं है।",
                "id": "Kode kesalahan ini belum ada di katalog.",
                "ar": "رمز العطل هذا غير موجود بعد في الكتالوج.",
                "ru": "Этого кода ошибки ещё нет в каталоге.",
                "de": "Dieser Fehlercode ist noch nicht im Katalog.",
                "fr": "Ce code défaut n’est pas encore dans le catalogue.",
                "ja": "この故障コードはまだカタログにありません。",
                "ko": "이 고장 코드는 아직 카탈로그에 없습니다.",
                "zh-Hans": "该故障码尚未收录到目录中。",
                "zh-Hant": "此故障碼尚未收錄於目錄中。",
                "vi": "Mã lỗi này chưa có trong danh mục.",
                "th": "ยังไม่มีรหัสความผิดปกตินี้ในแคตตาล็อก",
                "it": "Questo codice guasto non è ancora nel catalogo.",
                "pl": "Tego kodu usterki nie ma jeszcze w katalogu.",
                "nl": "Deze storingscode staat nog niet in de catalogus.",
                "ms": "Kod kerosakan ini belum ada dalam katalog.",
                "fil": "Wala pa ang fault code na ito sa katalogo.",
                "ur": "یہ خرابی کوڈ ابھی کیٹلاگ میں نہیں ہے۔",
                "bn": "এই ত্রুটি কোড এখনও ক্যাটালগে নেই।",
                "fa": "این کد خطا هنوز در کاتالوگ نیست.",
                "uk": "Цього коду несправності ще немає в каталозі.",
                "ro": "Acest cod de eroare nu este încă în catalog.",
                "cs": "Tento chybový kód zatím není v katalogu.",
                "sv": "Denna felkod finns ännu inte i katalogen.",
                "el": "Αυτός ο κωδικός βλάβης δεν υπάρχει ακόμη στον κατάλογο.",
                "he": "קוד התקלה הזה עדיין לא בקטלוג.",
                "hu": "Ez a hibakód még nincs a katalógusban.",
                "da": "Denne fejlkode er endnu ikke i kataloget.",
                "fi": "Tätä vikakoodia ei ole vielä luettelossa.",
                "nb": "Denne feilkoden er ikke i katalogen ennå.",
                "sk": "Tento chybový kód zatiaľ nie je v katalógu.",
                "hr": "Ovaj kod kvara još nije u katalogu.",
                "bg": "Този код на грешка все още не е в каталога.",
                "sw": "Msimbo huu wa hitilafu bado haupo kwenye katalogi.",
                "ca": "Aquest codi d’avaria encara no és al catàleg.",
            },
            "error.dtc.makeUnsupported": {
                "en": "Brand %@ is not in the catalog yet. Supported brands only.",
                "tr": "%@ markası henüz katalogda yok. Yalnızca desteklenen markalar.",
                "es": "La marca %@ aún no está en el catálogo. Solo marcas compatibles.",
                "es-419": "La marca %@ aún no está en el catálogo. Solo marcas compatibles.",
                "pt-BR": "A marca %@ ainda não está no catálogo. Apenas marcas compatíveis.",
                "pt-PT": "A marca %@ ainda não está no catálogo. Apenas marcas suportadas.",
                "hi": "ब्रांड %@ अभी कैटलॉग में नहीं है। केवल समर्थित ब्रांड।",
                "id": "Merek %@ belum ada di katalog. Hanya merek yang didukung.",
                "ar": "الماركة %@ غير موجودة بعد في الكتالوج. الماركات المدعومة فقط.",
                "ru": "Марки %@ ещё нет в каталоге. Только поддерживаемые марки.",
                "de": "Marke %@ ist noch nicht im Katalog. Nur unterstützte Marken.",
                "fr": "La marque %@ n’est pas encore dans le catalogue. Marques prises en charge uniquement.",
                "ja": "メーカー%@はまだカタログにありません。対応メーカーのみ。",
                "ko": "브랜드 %@는 아직 카탈로그에 없습니다. 지원 브랜드만 가능합니다.",
                "zh-Hans": "品牌 %@ 尚未收录。仅支持目录中的品牌。",
                "zh-Hant": "品牌 %@ 尚未收錄。僅支援目錄中的品牌。",
                "vi": "Hãng %@ chưa có trong danh mục. Chỉ các hãng được hỗ trợ.",
                "th": "ยังไม่มียี่ห้อ %@ ในแคตตาล็อก รองรับเฉพาะยี่ห้อที่มี",
                "it": "La marca %@ non è ancora nel catalogo. Solo marche supportate.",
                "pl": "Marki %@ nie ma jeszcze w katalogu. Tylko obsługiwane marki.",
                "nl": "Merk %@ staat nog niet in de catalogus. Alleen ondersteunde merken.",
                "ms": "Jenama %@ belum ada dalam katalog. Jenama disokong sahaja.",
                "fil": "Wala pa ang brand na %@ sa katalogo. Mga suportadong brand lang.",
                "ur": "برانڈ %@ ابھی کیٹلاگ میں نہیں ہے۔ صرف سپورٹڈ برانڈز۔",
                "bn": "ব্র্যান্ড %@ এখনও ক্যাটালগে নেই। শুধু সমর্থিত ব্র্যান্ড।",
                "fa": "برند %@ هنوز در کاتالوگ نیست. فقط برندهای پشتیبانی‌شده.",
                "uk": "Марки %@ ще немає в каталозі. Лише підтримувані марки.",
                "ro": "Marca %@ nu este încă în catalog. Doar mărci acceptate.",
                "cs": "Značka %@ zatím není v katalogu. Pouze podporované značky.",
                "sv": "Märket %@ finns ännu inte i katalogen. Endast stödda märken.",
                "el": "Η μάρκα %@ δεν υπάρχει ακόμη στον κατάλογο. Μόνο υποστηριζόμενες μάρκες.",
                "he": "המותג %@ עדיין לא בקטלוג. מותגים נתמכים בלבד.",
                "hu": "A(z) %@ márka még nincs a katalógusban. Csak támogatott márkák.",
                "da": "Mærket %@ er endnu ikke i kataloget. Kun understøttede mærker.",
                "fi": "Merkkiä %@ ei ole vielä luettelossa. Vain tuetut merkit.",
                "nb": "Merket %@ er ikke i katalogen ennå. Kun støttede merker.",
                "sk": "Značka %@ zatiaľ nie je v katalógu. Len podporované značky.",
                "hr": "Marke %@ još nema u katalogu. Samo podržane marke.",
                "bg": "Марка %@ все още не е в каталога. Само поддържани марки.",
                "sw": "Chapa %@ bado haipo kwenye katalogi. Chapa zinazotumika tu.",
                "ca": "La marca %@ encara no és al catàleg. Només marques compatibles.",
            },
            "error.dtc.notForMake": {
                "en": "%@ is not listed for %@ — manufacturer-specific codes differ by brand.",
                "tr": "%@ kodu %@ için tanımlı değil — üreticiye özel kodlar markaya göre değişir.",
                "es": "%@ no está listado para %@ — los códigos del fabricante varían por marca.",
                "es-419": "%@ no está listado para %@ — los códigos del fabricante varían por marca.",
                "pt-BR": "%@ não está listado para %@ — códigos do fabricante diferem por marca.",
                "pt-PT": "%@ não está listado para %@ — os códigos do fabricante diferem por marca.",
                "hi": "%@ कोड %@ के लिए सूचीबद्ध नहीं — निर्माता कोड ब्रांड के अनुसार भिन्न होते हैं।",
                "id": "%@ tidak terdaftar untuk %@ — kode khusus pabrikan berbeda per merek.",
                "ar": "%@ غير مدرج لـ %@ — رموز الشركة المصنعة تختلف حسب الماركة.",
                "ru": "%@ не указан для %@ — заводские коды различаются по маркам.",
                "de": "%@ ist für %@ nicht hinterlegt — herstellerspezifische Codes unterscheiden sich.",
                "fr": "%@ n’est pas répertorié pour %@ — les codes constructeur varient selon la marque.",
                "ja": "%@は%@向けに登録されていません — メーカー固有コードはブランドで異なります。",
                "ko": "%@는 %@에 등록되어 있지 않습니다 — 제조사별 코드는 브랜드마다 다릅니다.",
                "zh-Hans": "%@ 未列入 %@ — 厂商专用代码因品牌而异。",
                "zh-Hant": "%@ 未列入 %@ — 原廠專用代碼因品牌而異。",
                "vi": "%@ không có trong danh mục cho %@ — mã riêng của hãng khác nhau theo thương hiệu.",
                "th": "%@ ไม่ได้อยู่ในรายการของ %@ — รหัสเฉพาะผู้ผลิตต่างกันตามยี่ห้อ",
                "it": "%@ non è elencato per %@ — i codici del produttore variano per marca.",
                "pl": "%@ nie jest na liście dla %@ — kody producenta różnią się według marki.",
                "nl": "%@ staat niet vermeld voor %@ — fabrikantspecifieke codes verschillen per merk.",
                "ms": "%@ tidak disenaraikan untuk %@ — kod khusus pengeluar berbeza mengikut jenama.",
                "fil": "Hindi nakalista ang %@ para sa %@ — magkaiba ang manufacturer-specific codes bawat brand.",
                "ur": "%@ کوڈ %@ کے لیے درج نہیں — مینوفیکچرر کوڈز برانڈ کے لحاظ سے مختلف ہوتے ہیں۔",
                "bn": "%@ কোড %@-এর জন্য তালিকাভুক্ত নয় — প্রস্তুতকারকের কোড ব্র্যান্ডভেদে আলাদা।",
                "fa": "%@ برای %@ فهرست نشده — کدهای اختصاصی سازنده بر اساس برند متفاوت است.",
                "uk": "%@ не вказано для %@ — коди виробника різняться залежно від марки.",
                "ro": "%@ nu este listat pentru %@ — codurile producătorului diferă pe marcă.",
                "cs": "%@ není uvedeno pro %@ — kódy výrobce se liší podle značky.",
                "sv": "%@ finns inte listad för %@ — tillverkarspecifika koder skiljer sig per märke.",
                "el": "Το %@ δεν αναφέρεται για %@ — οι κωδικοί κατασκευαστή διαφέρουν ανά μάρκα.",
                "he": "%@ אינו רשום עבור %@ — קודי יצרן משתנים לפי מותג.",
                "hu": "A(z) %@ nincs listázva a(z) %@ számára — a gyártói kódok márkánként eltérnek.",
                "da": "%@ er ikke listet for %@ — producentkoder varierer pr. mærke.",
                "fi": "%@ ei ole listattu merkillä %@ — valmistajakohtaiset koodit vaihtelevat.",
                "nb": "%@ er ikke oppført for %@ — produsentspesifikke koder varierer per merke.",
                "sk": "%@ nie je uvedené pre %@ — kódy výrobcu sa líšia podľa značky.",
                "hr": "%@ nije naveden za %@ — proizvođački kodovi razlikuju se po marki.",
                "bg": "%@ не е в списъка за %@ — кодовете на производителя се различават по марка.",
                "sw": "%@ haijaorodheshwa kwa %@ — misimbo ya mtengenezaji hutofautiana kwa chapa.",
                "ca": "%@ no està llistat per a %@ — els codis del fabricant varien per marca.",
            },
            "result.brandSpecific": {
                "en": "Make-specific repair guidance",
                "tr": "Markaya özel tamir rehberi",
                "es": "Guía de reparación específica de la marca",
                "es-419": "Guía de reparación específica de la marca",
                "pt-BR": "Orientação de reparo específica da marca",
                "pt-PT": "Orientação de reparação específica da marca",
                "hi": "मेक-विशिष्ट मरम्मत मार्गदर्शन",
                "id": "Panduan perbaikan khusus merek",
                "ar": "إرشاد إصلاح خاص بالماركة",
                "ru": "Ремонтные рекомендации для марки",
                "de": "Markenspezifische Reparaturhilfe",
                "fr": "Guide de réparation spécifique à la marque",
                "ja": "メーカー別の修理ガイド",
                "ko": "브랜드별 수리 안내",
                "zh-Hans": "品牌专属维修指引",
                "zh-Hant": "品牌專屬維修指引",
                "vi": "Hướng dẫn sửa chữa theo hãng",
                "th": "คำแนะนำการซ่อมเฉพาะยี่ห้อ",
                "it": "Guida alla riparazione specifica per marca",
                "pl": "Wskazówki naprawy dla marki",
                "nl": "Merk-specifieke reparatiehulp",
                "ms": "Panduan pembaikan khusus jenama",
                "fil": "Gabay sa pagkumpuni para sa brand",
                "ur": "برانڈ مخصوص مرمت رہنمائی",
                "bn": "ব্র্যান্ড-নির্দিষ্ট মেরামত নির্দেশনা",
                "fa": "راهنمای تعمیر اختصاصی برند",
                "uk": "Ремонтні поради для марки",
                "ro": "Ghid de reparație specific mărcii",
                "cs": "Pokyny k opravě pro značku",
                "sv": "Märkesspecifik reparationsvägledning",
                "el": "Οδηγίες επισκευής ανά μάρκα",
                "he": "הנחיות תיקון ספציפיות למותג",
                "hu": "Márkaspecifikus javítási útmutató",
                "da": "Mærkespecifik reparationsvejledning",
                "fi": "Merkkikohtainen korjausohje",
                "nb": "Merke-spesifikk reparasjonsveiledning",
                "sk": "Pokyny na opravu pre značku",
                "hr": "Vodič za popravak za marku",
                "bg": "Указания за ремонт по марка",
                "sw": "Mwongozo wa ukarabati wa chapa",
                "ca": "Guia de reparació específica de la marca",
            },
        }
    )


def main() -> None:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from generate_localizations_rest import apply_rest

    _fill_remaining()
    _fill_errors_and_result()
    apply_rest(T)

    missing = []
    for key, locs in T.items():
        for lang in LANGS:
            if lang not in locs:
                missing.append(f"{key}:{lang}")
    if missing:
        raise SystemExit(f"Missing {len(missing)} translations, e.g. {missing[:10]}")

    catalog = {
        "sourceLanguage": "en",
        "strings": {
            key: {
                "localizations": {
                    lang: {"stringUnit": {"state": "translated", "value": locs[lang]}}
                    for lang in LANGS
                }
            }
            for key, locs in T.items()
        },
        "version": "1.0",
    }
    OUT.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(T)} keys × {len(LANGS)} languages")


if __name__ == "__main__":
    main()
